version: '3.8'

volumes:
  mariadb-data:

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env

    volumes:
      - ..:/workspaces:cached

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/MARIADB
    env_file:
      - .env
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward DB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
