#ifndef STRING_IDS
#define STRING_IDS

//These strings are loaded from eqstr_us.txt, but may vary between client versions. Maybe we could make this an enum that's dependent on the client version?
namespace StringID {
	const uint16 GENERIC_9_STRINGS              = 1; //%1 %2 %3 %4 %5 %6 %7 %8 %9
	const uint16 TARGET_OUT_OF_RANGE            = 100; //Your target is out of range, get closer!
	const uint16 TARGET_NOT_FOUND               = 101; //Target player not found.
	const uint16 TRADE_CANCEL_LORE              = 104; //Trade cancelled, duplicated Lore Items would result.
	const uint16 CANNOT_BIND                    = 105; //You cannot form an affinity with this area. Try a city.
	const uint16 SPELL_DOES_NOT_WORK_HERE       = 106; //This spell does not work here.
	const uint16 SPELL_DOES_NOT_WORK_PLANE      = 107; //This spell does not work on this plane.
	const uint16 CANT_SEE_TARGET                = 108; //You cannot see your target.
	const uint16 WARCRY_ACTIVATE                = 110; //Your body rushes with courage as you hear the war cry!
	const uint16 FLESHBONE_FAILURE              = 111; //You must hold an item on your cursor from which bone can be created.
	const uint16 MGB_STRING                     = 113; //The next group buff you cast will hit all targets in range.
	const uint16 ABILITY_FAILED                 = 116; //Your ability failed. Timer has been reset.
	const uint16 ESCAPE                         = 114; //You escape from combat, hiding yourself from view.
	const uint16 AA_OFF                         = 119; //Alternate Experience is *OFF*.
	const uint16 AA_ON                          = 121; //Alternate Experience is *ON*.
	const uint16 CANT_HIT_THEM                  = 123; //You can't hit them from here.
	const uint16 TARGET_TOO_FAR                 = 124; //Your target is too far away, get closer!
	const uint16 PROC_TOOLOW                    = 126; //Your will is not sufficient to command this weapon.
	const uint16 PROC_PETTOOLOW                 = 127; //Your pet's will is not sufficient to command its weapon.
	const uint16 YOU_FLURRY                     = 128; //You unleash a flurry of attacks.
	const uint16 FAILED_DISARM_TRAP             = 129; //You failed to disarm the trap.
	const uint16 DOORS_LOCKED                   = 130; //It's locked and you're not holding the key.
	const uint16 DOORS_CANT_PICK                = 131; //This lock cannot be picked.
	const uint16 DOORS_INSUFFICIENT_SKILL       = 132; //You are not sufficiently skilled to pick this lock.
	const uint16 DOORS_GM                       = 133; //You opened the locked door with your magic GM key.
	const uint16 ITEMS_INSUFFICIENT_LEVEL       = 136; //You are not sufficient level to use this item.
	const uint16 GAIN_XP                        = 138; //You gain experience!!
	const uint16 GAIN_GROUPXP                   = 139; //You gain party experience!!
	const uint16 AA_CAP_REACHED                 = 140; //You must spend some of your ability points.You will no longer gain ability points.
	const uint16 HANDS_MAGIC                    = 141; //Your hands are now magic weapons
	const uint16 BOW_DOUBLE_DAMAGE              = 143; //Your bow shot did double dmg.
	const uint16 NO_BANDAGES                    = 146; //You can't bandage without bandages, go buy some.
	const uint16 STAY_STILL                     = 147; //You are being bandaged. Stay relatively still.
	const uint16 FORAGE_COMBAT                  = 148; //You can't try to forage while attacking.
	const uint16 FORAGE_STANDING                = 149; //You must be standing to forage.
	const uint16 FORAGE_GRUBS                   = 150; //You have scrounged up some fishing grubs.
	const uint16 FORAGE_WATER                   = 151; //You have scrounged up some water.
	const uint16 FORAGE_FOOD                    = 152; //You have scrounged up some food.
	const uint16 FORAGE_DRINK                   = 153; //You have scrounged up some drink.
	const uint16 FORAGE_NOEAT                   = 154; //You have scrounged up something that doesn't look edible.
	const uint16 FORAGE_FAILED                  = 155; //You fail to locate any food nearby.
	const uint16 ALREADY_FISHING                = 156; //You are already fishing!
	const uint16 FISHING_HANDS_FULL             = 158; //You can't fish while holding something.
	const uint16 FISHING_NO_POLE                = 160; //You can't fish without a fishing pole, go buy one.
	const uint16 FISHING_EQUIP_POLE             = 161; //You need to put your fishing pole in your primary hand.
	const uint16 FISHING_NO_BAIT                = 162; //You can't fish without fishing bait, go buy some.
	const uint16 FISHING_CAST                   = 163; //You cast your line.
	const uint16 NOT_SCARING                    = 164; //You're not scaring anyone.
	const uint16 FISHING_STOP                   = 165; //You stop fishing and go on your way.
	const uint16 FISHING_LAND                   = 166; //Trying to catch land sharks perhaps?
	const uint16 FISHING_LAVA                   = 167; //Trying to catch a fire elemental or something?
	const uint16 FISHING_FAILED                 = 168; //You didn't catch anything.
	const uint16 FISHING_POLE_BROKE             = 169; //Your fishing pole broke!
	const uint16 FISHING_SUCCESS_SOMETHING      = 170; //You caught, something...
	const uint16 FISHING_SPILL_BEER             = 171; //You spill your beer while bringing in your line.
	const uint16 FISHING_LOST_BAIT              = 172; //You lost your bait!
	const uint16 SPELL_FIZZLE                   = 173; //Your spell fizzles!
	const uint16 FEIGN_BROKEN_CAST              = 176; //You are no longer feigning death, because you cast a spell.
	const uint16 MUST_EQUIP_ITEM                = 179; //You cannot use this item unless it is equipped.
	const uint16 MISS_NOTE                      = 180; //You miss a note, bringing your song to a close!
	const uint16 CANNOT_USE_ITEM                = 181; //Your race, class, or deity cannot use this item.
	const uint16 ITEM_OUT_OF_CHARGES            = 182; //Item is out of charges.
	const uint16 CANNOT_SUMMON_MOUNT_HERE       = 186; //You can not summon a mount here.
	const uint16 ALREADY_ON_A_MOUNT             = 189; //You are already on a mount.
	const uint16 TARGET_NO_MANA                 = 191; //Your target has no mana to affect
	const uint16 TARGET_GROUP_MEMBER            = 196; //You must first target a group member.
	const uint16 SPELL_TOO_POWERFUL             = 197; //Your spell is too powerful for your intended target.
	const uint16 INSUFFICIENT_MANA              = 199; //Insufficient Mana to cast this spell!
	const uint16 SAC_TOO_LOW                    = 203; //This being is not a worthy sacrifice.
	const uint16 SAC_TOO_HIGH                   = 204; //This being is too powerful to be a sacrifice.
	const uint16 CANNOT_SAC_SELF                = 205; //You cannot sacrifice yourself.
	const uint16 SILENCED_STRING                = 207; //You *CANNOT* cast spells, you have been silenced!
	const uint16 CAST_DAYTIME                   = 208; //Spell can only be cast during the day.
	const uint16 CAST_NIGHTTIME                 = 209; //Spell can only be cast during the night.
	const uint16 CANNOT_AFFECT_PC               = 210; //That spell can not affect this target PC.
	const uint16 SPELL_NEED_TAR                 = 214; //You must first select a target for this spell!
	const uint16 CORPSE_SUMMON_TAR              = 215; //You must first target a living group member whose corpse you wish to summon.
	const uint16 ONLY_ON_CORPSES                = 221; //This spell only works on corpses.
	const uint16 CANT_DRAIN_SELF                = 224; //You can't drain yourself!
	const uint16 CORPSE_NOT_VALID               = 230; //This corpse is not valid.
	const uint16 CORPSE_TOO_OLD                 = 231; //This player cannot be resurrected. The corpse is too old.
	const uint16 CAST_OUTDOORS                  = 234; //You can only cast this spell in the outdoors.
	const uint16 CAST_DUNGEONS                  = 235; //You can only cast this spell in dungeons.
	const uint16 SPELL_RECAST                   = 236; //Spell recast time not yet met.
	const uint16 SPELL_RECOVERY                 = 237; //Spell recovery time not yet met.
	const uint16 SUCCOR_FAIL                    = 238; //Your Portal fails to open.
	const uint16 CANNOT_MEZ                     = 239; //Your target cannot be mesmerized.
	const uint16 CANNOT_MEZ_WITH_SPELL          = 240; //Your target cannot be mesmerized (with this spell).
	const uint16 IMMUNE_STUN                    = 241; //Your target is immune to the stun portion of this effect.
	const uint16 IMMUNE_ATKSPEED                = 242; //Your target is immune to changes in its attack speed.
	const uint16 IMMUNE_FEAR                    = 243; //Your target is immune to fear spells.
	const uint16 IMMUNE_MOVEMENT                = 244; //Your target is immune to changes in its run speed.
	const uint16 ONLY_ONE_PET                   = 246; //You cannot have more than one pet at a time.
	const uint16 CANNOT_CHARM_YET               = 248; //Your target is too high of a level for your charm spell.
	const uint16 NO_COMPONENT_LUCLIN            = 249; //You don't have the correct component to travel to Luclin.
	const uint16 CANNOT_AFFECT_NPC              = 251; //That spell can not affect this target NPC.
	const uint16 FEIGN_BROKEN_SPELL             = 254; //You are no longer feigning death, because a spell hit you.
	const uint16 SUSPEND_MINION_HAS_AGGRO       = 256; //Your pet is the focus of something's attention.
	const uint16 CANNOT_TRANSLOCATE_SELF        = 257; //You can only translocate others!
	const uint16 NO_PET                         = 255; //You do not have a pet.
	const uint16 GATE_FAIL                      = 260; //Your gate is too unstable, and collapses.
	const uint16 CORPSE_CANT_SENSE              = 262; //You cannot sense any corpses for this PC in this zone.
	const uint16 SPELL_NO_HOLD                  = 263; //Your spell did not take hold.
	const uint16 CANNOT_CHARM                   = 267; //This NPC cannot be charmed.
	const uint16 SPELL_NO_EFFECT                = 268; //Your target looks unaffected.
	const uint16 NO_INSTRUMENT_SKILL            = 269; //Stick to singing until you learn to play this instrument.
	const uint16 REGAIN_AND_CONTINUE            = 270; //You regain your concentration and continue your casting.
	const uint16 SPELL_WOULDNT_HOLD             = 271; //Your spell would not have taken hold on your target.
	const uint16 MISSING_SPELL_COMP             = 272; //You are missing some required spell components.
	const uint16 INVIS_BEGIN_BREAK              = 275; //You feel yourself starting to appear.
	const uint16 FEIGN_BROKEN_MOVE              = 276; //You are no longer feigning death, because you moved.
	const uint16 WARCRY_FADES                   = 277; //The war cry fades.
	const uint16 DISCIPLINE_CONLOST             = 278; //You lose the concentration to remain in your fighting discipline.
	const uint16 DISCIPLINE_MONK_CONLOST        = 279; //Your iron will wavers, you are no longer in your fighting discipline.
	const uint16 REZ_REGAIN                     = 289; //You regain some experience from resurrection.
	const uint16 DUP_LORE                       = 290; //Duplicate lore items are not allowed.
	const uint16 TGB_ON                         = 293; //Target other group buff is *ON*.
	const uint16 TGB_OFF                        = 294; //Target other group buff is *OFF*.
	const uint16 TARGET_NOT_FOUND2              = 303; //I don't see anyone by that name around here...
	const uint16 DISARMED_TRAP                  = 305; //You have disarmed the trap.
	const uint16 TRADESKILL_NOCOMBINE           = 334; //You cannot combine these items in this container type!
	const uint16 TRADESKILL_FAILED              = 336; //You lacked the skills to fashion the items together.
	const uint16 TRADESKILL_TRIVIAL             = 338; //You can no longer advance your skill from making this item.
	const uint16 TRADESKILL_SUCCEED             = 339; //You have fashioned the items together to create something new!
	const uint16 EVADE_SUCCESS                  = 343; //You have momentarily ducked away from the main combat.
	const uint16 EVADE_FAIL                     = 344; //Your attempts at ducking clear of combat fail.
	const uint16 HIDE_FAIL                      = 345; //You failed to hide yourself.
	const uint16 HIDE_SUCCESS                   = 346; //You have hidden yourself from view.
	const uint16 SNEAK_SUCCESS                  = 347; //You are as quiet as a cat stalking its prey.
	const uint16 SNEAK_FAIL                     = 348; //You are as quiet as a herd of running elephants.
	const uint16 MEND_CRITICAL                  = 349; //You magically mend your wounds and heal considerable damage.
	const uint16 MEND_SUCCESS                   = 350; //You mend your wounds and heal some damage.
	const uint16 MEND_WORSEN                    = 351; //You have worsened your wounds!
	const uint16 MEND_FAIL                      = 352; //You have failed to mend your wounds.
	const uint16 TRAP_NOT_DETECTED              = 367; //You have not detected any traps.
	const uint16 TRAP_TOO_FAR                   = 368; //You are too far away from that trap to affect it.
	const uint16 FAIL_DISARM_DETECTED_TRAP      = 370; //You fail to disarm the detected trap.
	const uint16 LOOT_LORE_ERROR                = 371; //You cannot loot this Lore Item. You already have one.
	const uint16 PICK_LORE                      = 379; //You cannot pick up a lore item you already possess.
	const uint16 CORPSE_TOO_FAR                 = 389; //The corpse is too far away to summon.
	const uint16 CONSENT_NONE                   = 390; //You do not have consent to summon that corpse.
	const uint16 DISCIPLINE_RDY                 = 393; //You are ready to use a new discipline now.
	const uint16 CONSENT_INVALID_NAME           = 397; //Not a valid consent name.
	const uint16 CONSENT_NPC                    = 398; //You cannot consent NPC\'s.
	const uint16 CONSENT_YOURSELF               = 399; //You cannot consent yourself.
	const uint16 SONG_NEEDS_DRUM                = 405; //You need to play a percussion instrument for this song
	const uint16 SONG_NEEDS_WIND                = 406; //You need to play a wind instrument for this song
	const uint16 SONG_NEEDS_STRINGS             = 407; //You need to play a stringed instrument for this song
	const uint16 SONG_NEEDS_BRASS               = 408; //You need to play a brass instrument for this song
	const uint16 AA_GAIN_ABILITY                = 410; //You have gained the ability "%T1" at a cost of %2 ability %T3.
	const uint16 AA_IMPROVE                     = 411; //You have improved %T1 %2 at a cost of %3 ability %T4.
	const uint16 TAUNT_SUCCESS                  = 412; //You taunt %1 to ignore others and attack you!
	const uint16 AA_REUSE_MSG                   = 413; //You can use the ability %T1 again in %2 hour(s) %3 minute(s) %4 seconds.
	const uint16 AA_REUSE_MSG2                  = 414; //You can use the ability %T1 again in %2 minute(s) %3 seconds.
	const uint16 YOU_HEALED                     = 419; //You have been healed for %1 points of damage.
	const uint16 FISHING_SUCCESS                = 421; //You caught % 1!
	const uint16 BEGINS_TO_GLOW                 = 422; //Your %1 begins to glow.
	const uint16 ALREADY_INVIS                  = 423; //%1 tries to cast an invisibility spell on you, but you are already invisible.
	const uint16 YOU_ARE_PROTECTED              = 424; //%1 tries to cast a spell on you, but you are protected.
	const uint16 TARGET_RESISTED                = 425; //Your target resisted the %1 spell.
	const uint16 YOU_RESIST                     = 426; //You resist the %1 spell!
	const uint16 YOU_CRIT_HEAL                  = 427; //You perform an exceptional heal! (%1)
	const uint16 YOU_CRIT_BLAST                 = 428; //You deliver a critical blast! (%1)
	const uint16 SUMMONING_CORPSE               = 429; //Summoning your corpse.
	const uint16 SUMMONING_CORPSE_OTHER         = 430; //Summoning %1's corpse.
	const uint16 MISSING_SPELL_COMP_ITEM        = 433; //You are missing %1.
	const uint16 OTHER_HIT_NONMELEE             = 434; //%1 was hit by non-melee for %2 points of damage.
	const uint16 PET_SPELL_WORN_OFF             = 435; //Your pet's %1 spell has worn off.
	const uint16 SPELL_WORN_OFF_OF              = 436; //Your %1 spell has worn off of %2.
	const uint16 SPELL_WORN_OFF                 = 437; //Your %1 spell has worn off.
	const uint16 PET_TAUNTING                   = 438; //Taunting attacker, Master.
	const uint16 INTERRUPT_SPELL                = 439; //Your spell is interrupted.
	const uint16 LOSE_LEVEL                     = 442; //You LOST a level! You are now level %1!
	const uint16 GAIN_ABILITY_POINT             = 446; //You have gained an ability point! You now have %1 ability point%2.
	const uint16 GAIN_LEVEL                     = 447; //You have gained a level! Welcome to level %1!
	const uint16 LANG_SKILL_IMPROVED            = 449; //Your language skills have improved.
	const uint16 OTHER_LOOTED_MESSAGE           = 466; //--%1 has looted a %2--
	const uint16 LOOTED_MESSAGE                 = 467; //--You have looted a %1--
	const uint16 FACTION_WORST                  = 469; //Your faction standing with %1 could not possibly get any worse.
	const uint16 FACTION_WORSE                  = 470; //Your faction standing with %1 got worse.
	const uint16 FACTION_BEST                   = 471; //Your faction standing with %1 could not possibly get any better.
	const uint16 FACTION_BETTER                 = 472; //Your faction standing with %1 got better.
	const uint16 PET_REPORT_HP                  = 488; //I have %1 percent of my hit points left.
	const uint16 PET_NO_TAUNT                   = 489; //No longer taunting attackers, Master.
	const uint16 PET_DO_TAUNT                   = 490; //Taunting attackers as normal, Master.
	const uint16 CORPSE_DECAY1                  = 495; //This corpse will decay in %1 minute(s) %2 seconds.
	const uint16 DISC_LEVEL_ERROR               = 503; //You must be a level %1 ... to use this discipline.
	const uint16 DISCIPLINE_CANUSEIN            = 504; //You can use a new discipline in %1 minutes %2 seconds.
	const uint16 SHARE_MONEY                    = 511; //%1 shares money with the group.
	const uint16 PVP_ON                         = 552; //You are now player kill and follow the ways of Discord.
	const uint16 TARGET_CURED                   = 553; //Your target has been cured.
	const uint16 GENERIC_STRINGID_SAY           = 554; //%1 says '%T2'
	const uint16 CANNOT_WAKE                    = 555; //%1 tells you, 'I am unable to wake %2, master.'
	const uint16 GUILD_NAME_IN_USE              = 711; //You cannot create a guild with that name, that guild already exists on this server.
	const uint16 AA_POINTS_CAP                  = 1000; //You cannot gain any further alternate advancement experience.Please spend some points.
	const uint16 GM_GAINXP                      = 1002; //[GM] You have gained %1 AXP and %2 EXP (%3).
	const uint16 MALE_SLAYUNDEAD                = 1007; //%1's holy blade cleanses his target!(%2)
	const uint16 FEMALE_SLAYUNDEAD              = 1008; //%1's holy blade cleanses her target!(%2)
	const uint16 FINISHING_BLOW                 = 1009; //%1 scores a Finishing Blow!!
	const uint16 ASSASSINATES                   = 1016; //%1 ASSASSINATES their victim!!
	const uint16 ASHEN_CRIT                     = 1017; //% 1's ashen hand of death causes %2's heart to stop.
	const uint16 SILENT_FIST_TAIL               = 1018; //% 1's tail of fury stuns %2.
	const uint16 SILENT_FIST_CRIT               = 1019; //% 1's Silent fist of fury stuns %2.
	const uint16 THUNDEROUS_KICK                = 1020; //% 1 Lands a Thunderous Kick(% 2).
	const uint16 CRIPPLING_BLOW                 = 1021; //%1 lands a Crippling Blow!(%2)
	const uint16 CRITICAL_HIT                   = 1023; //%1 scores a critical hit! (%2)
	const uint16 DEADLY_STRIKE                  = 1024; //%1 scores a Deadly Strike!(%2)
	const uint16 RESISTS_URGE                   = 1025; //%1 resists their urge to flee.
	const uint16 BERSERK_START                  = 1027; //%1 goes into a berserker frenzy!
	const uint16 DEATH_PACT                     = 1028; //%1's death pact has been benevolently fulfilled!
	const uint16 DIVINE_INTERVENTION            = 1029; //%1 has been rescued by divine intervention!
	const uint16 BERSERK_END                    = 1030; //%1 is no longer berserk.
	const uint16 GATES                          = 1031; //%1 Gates.
	const uint16 GENERIC_SAY                    = 1032; //%1 says '%2'
	const uint16 OTHER_REGAIN_CAST              = 1033; //%1 regains concentration and continues casting.
	const uint16 GENERIC_SHOUT                  = 1034; //%1 shouts '%2'
	const uint16 GENERIC_EMOTE                  = 1036; //%1 %2
	const uint16 BEGIN_GATE                     = 1038; //%1 begins to cast the gate spell.
	const uint16 OTHER_CRIT_HEAL                = 1039; //%1 performs an exceptional heal! (%2)
	const uint16 OTHER_CRIT_BLAST               = 1040; //%1 delivers a critical blast! (%2)
	const uint16 NPC_ENRAGE_START               = 1042; //%1 has become ENRAGED.
	const uint16 NPC_ENRAGE_END                 = 1043; //%1 is no longer enraged.
	const uint16 NPC_RAMPAGE                    = 1044; //%1 goes on a RAMPAGE!
	const uint16 NPC_FLURRY                     = 1045; //%1 executes a FLURRY of attacks on %2!
	const uint16 DISCIPLINE_AGRESSIVE           = 1048; //%1 assumes an aggressive fighting style.
	const uint16 DISCIPLINE_PRECISION           = 1049; //%1 assumes a highly precise fighting style.
	const uint16 DISCIPLINE_DEFENSIVE           = 1050; //%1 assumes a defensive fighting style.
	const uint16 DISCIPLINE_EVASIVE             = 1051; //%1 assumes an evasive fighting style.
	const uint16 DISCIPLINE_SILENTFIST          = 1052; //%1's fist clenches in silent but deadly fury.
	const uint16 DISCIPLINE_ASHENHAND           = 1053; //%1's fist clenches with fatal fervor.
	const uint16 DISCIPLINE_SILENTFIST_IKSAR    = 1054; //%1's tail twitches in silent but deadly fury.
	const uint16 DISCIPLINE_FURIOUS             = 1055; //%1's face becomes twisted with fury.
	const uint16 DISCIPLINE_STONESTANCE         = 1056; //%1's feet become one with the earth.
	const uint16 DISCIPLINE_THUNDERKICK         = 1057; //%1's feet glow with mystical power.
	const uint16 DISCIPLINE_FORTITUDE           = 1058; //%1 becomes untouchable.
	const uint16 DISCIPLINE_FELLSTRIKE          = 1059; //%1's muscles bulge with force of will.
	const uint16 DISCIPLINE_NIMBLE              = 1060; //%1's reflexes become sharpened by concentrated efforts.
	const uint16 DISCIPLINE_CHARGE              = 1061; //%1 feels unstoppable!
	const uint16 DISCIPLINE_MIGHTYSTRIKE        = 1062; //%1 feels like a killing machine!
	const uint16 DISCIPLINE_HUNDREDFIST         = 1063; //%1 assumes an intimidating demeanor.
	const uint16 DISCIPLINE_KINESTHETICS        = 1064; //%1 arms feel alive with mystical energy.
	const uint16 DISCIPLINE_HOLYFORGE           = 1065; //%1's weapon is bathed in a holy light.
	const uint16 DISCIPLINE_SANCTIFICATION      = 1066; //A sanctifying aura surrounds %1.
	const uint16 DISCIPLINE_TRUESHOT            = 1067; //%1's bow crackles with natural energy.
	const uint16 DISCIPLINE_WPNSLD_MALE         = 1068; //%1 deftly twirls his weapon(s).
	const uint16 DISCIPLINE_WPNSLD_FEMALE       = 1069; //%1 deftly twirls her weapon(s).
	const uint16 DISCIPLINE_WPNSLD_MONSTER      = 1070; //%1 deftly twirls its weapon(s).
	const uint16 DISCIPLINE_UNHOLYAURA          = 1071; //An unholy aura envelops %1.
	const uint16 DISCIPLINE_LEECHCURSE          = 1072; //%1's weapon pulsates with an eerie blue light.
	const uint16 DISCIPLINE_DEFTDANCE           = 1073; //%1 prances about nimbly.
	const uint16 DISCIPLINE_PURETONE            = 1074; //%1's voice becomes perfectly melodius.
	const uint16 DISCIPLINE_RESISTANT           = 1075; //%1 has become more resistant.
	const uint16 DISCIPLINE_FEARLESS            = 1076; //%1 becomes fearless.
	const uint16 DUEL_FINISHED                  = 1088; //dont know text
	const uint16 EATING_MESSAGE                 = 1091; //Chomp, chomp, chomp... %1 takes a bite from a %2.
	const uint16 DRINKING_MESSAGE               = 1093; //Glug, glug, glug... %1 takes a drink from a %2.
	const uint16 SUCCESSFUL_TAUNT               = 1095; //I'll teach you to interfere with me %3.
	const uint16 NO_NEED_FOR_ITEM               = 1105; //I have no need for this item %3, you can have it back.
	const uint16 DISARM_SUCCESS                 = 1109; //ARGGHH...My Weapon!
	const uint16 TRADE_BAD_FACTION1             = 1110; //Oh look..a talking lump of refuse..how novel!
	const uint16 TRADE_BAD_FACTION2             = 1111; //Is that your BREATH.. or did something die in here..now go away!
	const uint16 TRADE_BAD_FACTION3             = 1112; //I didn't know Slime could speak common..go back to the sewer before I lose my temper.
	const uint16 TRADE_BAD_FACTION4             = 1113; //I wonder how much I could get for the tongue of a blithering fool..leave before I decide to find out for myself.
	const uint16 PET_SIT_STRING                 = 1130; //Changing position, Master.
	const uint16 PET_CALMING                    = 1131; //Sorry, Master..calming down.
	const uint16 PET_FOLLOWING                  = 1132; //Following you, Master.
	const uint16 PET_GUARDME_STRING             = 1133; //Guarding you, Master.
	const uint16 PET_GUARDINGLIFE               = 1134; //Guarding with my life..oh splendid one.
	const uint16 PET_GETLOST_STRING             = 1135; //As you wish, oh great one.
	const uint16 PET_LEADERIS                   = 1136; //My leader is %3.
	const uint16 I_FOLLOW_NOONE                 = 1137; //I follow no one.
	const uint16 PET_ON_HOLD                    = 1138; //Waiting for your order to attack, Master.
	const uint16 NOT_LEGAL_TARGET               = 1139; //I beg forgiveness, Master. That is not a legal target.
	const uint16 MERCHANT_BUSY                  = 1143; //I'm sorry, I am busy right now.
	const uint16 MERCHANT_GREETING              = 1144; //Welcome to my shop, %3.
	const uint16 MERCHANT_HANDY_ITEM1           = 1145; //Hello there, %3. How about a nice %4?
	const uint16 MERCHANT_HANDY_ITEM2           = 1146; //Greetings, %3. You look like you could use a %4.
	const uint16 MERCHANT_HANDY_ITEM3           = 1147; //Hi there %3, just browsing? Have you seen the %4 I just got in?
	const uint16 MERCHANT_HANDY_ITEM4           = 1148; //Welcome to my shop, %3. You would probably find a %4 handy.
	const uint16 WONT_SELL_RACE1                = 1154; //I don't like to speak to %B3(12) much less sell to them!
	const uint16 WONT_SELL_CLASS1               = 1155; //It's %B3(13) like you that are ruining the continent...get OUT!
	const uint16 WONT_SELL_CLASS2               = 1156; //Isn't there some kind of ordinance against %B3(13) crawling out from under their rocks?
	const uint16 WONT_SELL_CLASS3               = 1157; //%B3(13) like you don't have any place in my shop..now make way for welcome customers.
	const uint16 WONT_SELL_CLASS4               = 1158; //I thought scumbag %B3(13) like you just stole whatever they need.  Now GET OUT!
	const uint16 WONT_SELL_RACE5                = 1159; //I don't have anything to do with %B3(13)..move along.
	const uint16 WONT_SELL_NONSTDRACE1          = 1160; //I don't have anything to do with your little gang..move along.
	const uint16 WONT_SELL_RACE2                = 1161; //It's not enough that you %B3(12) have ruined your own land. Now get lost!
	const uint16 WONT_SELL_RACE3                = 1162; //I have something here that %B3(12) use..let me see...it's the EXIT, now get LOST!
	const uint16 WONT_SELL_RACE4                = 1163; //Don't you %B3(12) have your own merchants?  Whatever, I'm not selling anything to you!
	const uint16 WONT_SELL_NONSTDRACE2          = 1164; //Members of your little "club" have ruined things around here..get lost!
	const uint16 WONT_SELL_NONSTDRACE3          = 1165; //I don't have anything to do with your damned club..move along.
	const uint16 WONT_SELL_DEEDS1               = 1166; //Creatures like you make me sick..the things you do..get out of here Pagan!
	const uint16 WONT_SELL_DEEDS2               = 1167; //After all the things you've done..the things you believe in..leave my shop!
	const uint16 WONT_SELL_DEEDS3               = 1168; //Actions speak louder than beliefs, and I despise both your actions and all you believe in.
	const uint16 WONT_SELL_DEEDS4               = 1169; //Get out of here now!
	const uint16 WONT_SELL_DEEDS5               = 1170; //I am tolerant by nature..but infidels like you push me past my limit..get out!
	const uint16 WONT_SELL_DEEDS6               = 1171; //I cannot abide you or your actions against all that is right..BE GONE!
	const uint16 BEG_FAIL1                      = 1192; //You have the audacity to beg from me??!
	const uint16 PP_FAIL                        = 1193; //Stop Thief! <%3>
	const uint16 BEG_FAIL2                      = 1194; //I Despise beggars, they are not fit to live.
	const uint16 BEG_SUCCESS                    = 1195; //Here %3 take this and LEAVE ME ALONE!
	const uint16 AA_POINT                       = 1197; //point
	const uint16 AA_POINTS                      = 1215; //points
	const uint16 SPELL_FIZZLE_OTHER             = 1218; //%1's spell fizzles!
	const uint16 MISSED_NOTE_OTHER              = 1219; //A missed note brings %1's song to a close!
	const uint16 SPELL_LEVEL_REQ                = 1226; //This spell only works on people who are level %1 and under.
	const uint16 CORPSE_DECAY_NOW               = 1227; //This corpse is waiting to expire.
	const uint16 CORPSE_ITEM_LOST               = 1228; //Your items will no longer stay with you when you respawn on death. You will now need to return to your corpse for your items.
	const uint16 CORPSE_EXP_LOST                = 1229; //You will now lose experience when you die.
	const uint16 FLICKERS_PALE_LIGHT            = 1230; //Your %1 flickers with a pale light.
	const uint16 PULSES_WITH_LIGHT              = 1231; //Your %1 pulses with light as your vision sharpens.
	const uint16 FEEDS_WITH_POWER               = 1232; //Your %1 feeds you with power.
	const uint16 POWER_DRAIN_INTO               = 1233; //You feel your power drain into your %1.
	const uint16 SEEMS_DRAINED                  = 1234; //Your %1 seems drained of power.
	const uint16 ALIVE_WITH_POWER               = 1235; //Your %1 feels alive with power.
	const uint16 SPARKLES                       = 1236; //Your %1 sparkles.
	const uint16 GROWS_DIM                      = 1237; //Your %1 grows dim.
	const uint16 BEGINS_TO_SHINE                = 1238; //Your %1 begins to shine.
	const uint16 SURNAME_REJECTED               = 1374; //Your new surname was rejected. Please try a different name.
	const uint16 ALREADY_SOLD                   = 1376; //The item you were interested in has already been sold.
	const uint16 DUEL_DECLINE                   = 1383; //%1 has declined your challenge to duel to the death.
	const uint16 DUEL_ACCEPTED                  = 1384; //%1 has already accepted a duel with someone else.
	const uint16 DUEL_CONSIDERING               = 1385; //%1 is considering a duel with someone else.
	const uint16 BEEN_SUMMONED                  = 1393; //You have been summoned!
	const uint16 PLAYER_REGAIN                  = 1394; //You have control of yourself again.
	const uint16 BIND_WOUND_COMPLETE            = 1398; //The bandaging is complete.
	const uint16 REZZ_ALREADY_PENDING           = 1379; //You were unable to restore the corpse to life, but you may have success with a later attempt.
	const uint16 IN_USE                         = 1406; //Someone else is using that. Try again later.
	const uint16 DUEL_FLED                      = 1408; //%1 has defeated %2 in a duel to the death! %3 has fled like a cowardly dog!
	const uint16 CONSENT_GIVEN                  = 1427; //You have given %1 permission to drag your corpse.
	const uint16 CONSENT_DENIED                 = 1428; //You have denied %1 permission to drag your corpse.
	const uint16 MEMBER_OF_YOUR_GUILD           = 1429;
	const uint16 OFFICER_OF_YOUR_GUILD          = 1430;
	const uint16 LEADER_OF_YOUR_GUILD           = 1431;
	const uint16 TRADE_NOBODY                   = 1444; //I'm not interested in trading with anyone at all.'
	const uint16 TRADE_GROUP_ONLY               = 1445; //I'm only interested in trading with members of my group.'
	const uint16 TRADE_BUSY                     = 1446; //%1 tells you, 'I'm busy right now.'
	const uint16 TRADE_INTERESTED               = 1447; //%1 is interested in making a trade.
	const uint16 TRADE_CANCELLED                = 1449; //The trade has been cancelled.
	const uint16 RECEIVED_PLATINUM              = 1452; //You receive %1 Platinum from %2.
	const uint16 RECEIVED_GOLD                  = 1453; //You receive %1 Gold from %2.
	const uint16 RECEIVED_SILVER                = 1454; //You receive %1 Silver from %2.
	const uint16 RECEIVED_COPPER                = 1455; //You receive %1 Copper from %2.
	const uint16 STRING_FEIGNFAILED             = 1456; //%1 has fallen to the ground.
	const uint16 DOORS_SUCCESSFUL_PICK          = 1457; //You successfully picked the lock.
	const uint16 PLAYER_CHARMED                 = 1461; //You lose control of yourself!
	const uint16 TRADER_BUSY                    = 1468; //That Trader is currently with a customer. Please wait until their transaction is finished.
	const uint16 SENSE_CORPSE_DIRECTION         = 1563; //You sense a corpse in this direction.
	const uint16 DUPE_LORE_MERCHANT             = 1573; //%1 tells you, 'You already have that Lore Item on your person or in the bank.  You cannot have more than one of a particular Lore Item at a time.'
	const uint16 CONSENT_BEEN_DENIED            = 2103; //You have been denied permission to drag %1's corpse.
	const uint16 SCUMSUCKERS                    = 2241; //Scumsuckers
	const uint16 QUEUED_TELL                    = 2458; //[queued]
	const uint16 QUEUE_TELL_FULL                = 2459; //[zoing and queue is full]
	const uint16 SUSPEND_MINION_UNSUSPEND       = 3267; //%1 tells you, 'I live again...'
	const uint16 SUSPEND_MINION_SUSPEND         = 3268; //%1 tells you, 'By your command, master.'
	const uint16 ONLY_SUMMONED_PETS             = 3269; //3269 This effect only works with summoned pets.
	const uint16 SUSPEND_MINION_FIGHTING        = 3270; //Your pet must be at peace, first.
	const uint16 SHIELD_TARGET_LIVING           = 3278; //You must first target a living Player Character.
	const uint16 ALREADY_SHIELDED               = 3279; //Either you or your target is already being shielded.
	const uint16 ALREADY_SHIELDING_ANOTHER      = 3280; //Either you or your target is already shielding another.
	const uint16 START_SHIELDING                = 3281; //%1 begins to use %2 as a living shield!
	const uint16 END_SHIELDING                  = 3282; //%1 ceases protecting %2.
	const uint16 DIV_ARB_GIVE                   = 3293; //You sacrifice some of your health for the benefit of your party.
	const uint16 DIV_ARB_TAKE                   = 3294; //The vitality sacrificed by your party floods into your being. 
	const uint16 NO_SUITABLE_CORPSE             = 3295; //You cannot see any suitable corpses from here.
	const uint16 YOU_BEGIN_TO_CONCENTRATE       = 3296; //You begin to concentrate on %1...
	const uint16 RISES_TO_SERVE                 = 3297; //%1 rises to serve %2.
	const uint16 TRADESKILL_MISSING_ITEM        = 3455; //You are missing a %1.
	const uint16 TRADESKILL_MISSING_COMPONENTS  = 3456; //Sorry, but you don't have everything you need for this recipe in your general inventory.
	const uint16 TRADESKILL_LEARN_RECIPE        = 3457; //You have learned the recipe %1!
	const uint16 GAINED_SHIELD_LEVEL            = 4032; //You have gained the ability to act as a Living Shield for others!Type / SHIELD for help.
	const uint16 SHIELD_NO_DISC                 = 4037; //Neither person in a / SHIELD link may be using a discipline.
	const uint16 REWIND_WAIT                    = 4059; //You must wait a bit longer before using the rewind command again.
	const uint16 CORPSEDRAG_LIMIT               = 4061; //You are already dragging as much as you can!
	const uint16 CORPSEDRAG_ALREADY             = 4062; //You are already dragging %1.
	const uint16 CORPSEDRAG_SOMEONE_ELSE        = 4063; //Someone else is dragging %1.
	const uint16 CORPSEDRAG_BEGIN               = 4064; //You begin to drag %1.
	const uint16 CORPSEDRAG_STOPALL             = 4065; //You stop dragging the corpses.
	const uint16 CORPSEDRAG_STOP                = 4066; //You stop dragging the corpse.
	const uint16 TARGET_TOO_CLOSE               = 4602; //You are too close to your target. Get farther away.
	const uint16 WHOALL_PLAYERS                 = 5001; //Players in EverQuest:
	const uint16 WHOALL_USERPID                 = 5004; //(USER PID % 1)
	const uint16 WHOALL_ZONE                    = 5006; //ZONE: % 1
	const uint16 WHOALL_STEWARD                 = 5007; //* Steward *
	const uint16 WHOALL_APPRENTICE              = 5008; //* Apprentice Guide *
	const uint16 WHOALL_GUIDE                   = 5009; //* Guide *
	const uint16 WHOALL_QUESTTROUPE             = 5010; //* QuestTroupe *
	const uint16 WHOALL_SENIOR                  = 5011; //* Senior Guide *
	const uint16 WHOALL_TESTER                  = 5012; //* GM - Tester *
	const uint16 WHOALL_EQSUPPORT               = 5013; //* EQ Support *
	const uint16 WHOALL_STAFF                   = 5014; //* GM - Staff *
	const uint16 WHOALL_ADMIN                   = 5015; //* GM - Admin *
	const uint16 WHOALL_LEAD                    = 5016; //* GM - Lead Admin *
	const uint16 WHOALL_QUESTMASTER             = 5017; //* QuestMaster *
	const uint16 WHOALL_AREAS                   = 5018; //* GM - Areas *
	const uint16 WHOALL_CODER                   = 5019; //* GM - Coder *
	const uint16 WHOALL_MGMT                    = 5020; //* GM - Mgmt *
	const uint16 WHOALL_IMPOSSIBRU              = 5021; //* GM - Impossible *
	const uint16 WHOALL_GM                      = 5022; //%T1[ANON (%2 %3)] %4 (%5) %6 %7 %8
	const uint16 WHOALL_ROLE                    = 5023; //%T1[ANONYMOUS] %2 %3 %4
	const uint16 WHOALL_ANON                    = 5024; //%T1[ANONYMOUS] %2 %3
	const uint16 WHOALL_ALL                     = 5025; //%T1[%2 %3] %4 (%5) %6 %7 %8 %9
	const uint16 WHOALL_SINGLE                  = 5028; //There is %1 player in EverQuest.
	const uint16 WHOALL_NO_RESULTS              = 5029; //There are no players in EverQuest that match those who filters.
	const uint16 WHOALL_CUT_SHORT               = 5033; //Your who request was cut short..too many players.
	const uint16 WHOALL_COUNT                   = 5036; //There are % 1 players in EverQuest.
	const uint16 GROUP_LEADER_DISBAND           = 5044; //The leader's group was disbanded before you accepted the invitation.
	const uint16 TELL_QUEUED_MESSAGE            = 5045; //You told %1 '%T2. %3'
	const uint16 TOLD_NOT_ONLINE                = 5046; //%1 is not online at this time.
	const uint16 RAID_IS_FULL                   = 5048; //The raid is full.
	const uint16 NO_EXPAN                       = 5052; //The zone that you are attempting to enter is part of an expansion that you do not yet own.You may need to return to the Login screen and enter an account key for that expansion.If you have received this message in error, please / petition or send an email to EQAccounts@soe.sony.com
	const uint16 PETITION_NO_DELETE             = 5053; //You do not have a petition in the queue.
	const uint16 PETITION_DELETED               = 5054; //Your petition was successfully deleted.
	const uint16 ALREADY_IN_RAID                = 5060; //%1 is already in a raid.
	const uint16 CANNOT_JOIN_RAID               = 5078; //You cannot join the raid because %1 is either linkdead or is not in the zone.
	const uint16 RAID_OOR                       = 5084; //A member of the group of the person you are inviting to the raid is out of range.The invite has failed.
	const uint16 GAIN_RAIDEXP                   = 5085; //You gained raid experience!
	const uint16 ALREADY_IN_GRP_RAID            = 5088; //% 1 rejects your invite because they are in a raid and you are not in theirs, or they are a raid group leader
	const uint16 DUNGEON_SEALED                 = 5141; //The gateway to the dungeon is sealed off to you.  Perhaps you would be able to enter if you needed to adventure there.
	const uint16 PET_ATTACKING                  = 5501; //%1 tells you, 'Attacking %2 Master.'
	const uint16 PROJECT_ILLUSION               = 5742; // The next illusion spell you cast that changes a player into another character model and not an object will work on the group member you have targeted.
	const uint16 FATAL_BOW_SHOT                 = 5745; //%1 performs a FATAL BOW SHOT!!
	const uint16 AVOID_STUN                     = 5753; //You avoid the stunning blow.
	const uint16 GENERIC_STRING                 = 6688; //%1 (used to any basic message)
	const uint16 DOORS_NO_PICK                  = 7564; //You must have a lock pick in your inventory to do this.
	const uint16 CURRENT_SPELL_EFFECTS          = 8757; //%1's current spell effects:
	const uint16 BUFF_MINUTES_REMAINING         = 8799; //%1 (%2 minutes remaining)
	const uint16 YOUR_HIT_DOT                   = 9072; //%1 has taken %2 damage from your %3.
	const uint16 AE_RAMPAGE                     = 11015; //%1 goes on a WILD RAMPAGE!
	const uint16 GROUP_IS_FULL                  = 12000; //You cannot join that group, it is full.
	const uint16 GROUP_REMOVED                  = 12001; //You have been removed from the group.
	const uint16 FACE_ACCEPTED                  = 12028; //Facial features accepted.
	const uint16 SPELL_NOT_RECOVERED            = 12029; //You haven't recovered yet...
	const uint16 ABORTED_SCRIBING_SPELL         = 12044; //Aborting scribing of spell.
	const uint16 SPELL_LEVEL_TO_LOW             = 12048; //You will have to achieve level %1 before you can scribe the %2.
	const uint16 MERCHANT_BUSY_TELL             = 12069; //%1 tells you, 'I'm busy with another customer now. Please come back later.'
	const uint16 YOU_RECEIVE_AS_SPLIT           = 12071; //You receive %1 as your split.
	const uint16 ATTACKFAILED                   = 12158; //%1 try to %2 %3, but %4!
	const uint16 HIT_STRING                     = 12183; //hit
	const uint16 CRUSH_STRING                   = 12191; //crush
	const uint16 PIERCE_STRING                  = 12193; //pierce
	const uint16 KICK_STRING                    = 12195; //kick
	const uint16 STRIKE_STRING                  = 12197; //strike
	const uint16 BACKSTAB_STRING                = 12199; //backstab
	const uint16 BASH_STRING                    = 12201; //bash
	const uint16 BEGIN_CAST_SPELL               = 12206; //%1 begins to cast a spell.
	const uint16 GUILD_NOT_MEMBER               = 12242; //You are not a member of any guild.
	const uint16 MEMBER_OF_X_GUILD              = 12256;
	const uint16 OFFICER_OF_X_GUILD             = 12257;
	const uint16 LEADER_OF_X_GUILD              = 12258;
	const uint16 NOT_IN_A_GUILD                 = 12259;
	const uint16 TARGET_PLAYER_FOR_GUILD_STATUS = 12260;
	const uint16 ALREADY_IN_GROUP               = 12265; //% 1 is already in another group.
	const uint16 GROUP_INVITEE_NOT_FOUND        = 12268; //You must target a player or use /invite <name> to invite someone to your group.
	const uint16 GROUP_INVITEE_SELF             = 12270; //12270 You cannot invite yourself.
	const uint16 GROUP_INVITED                  = 12280; //%1 invites you to join a group.
	const uint16 CANNOT_JOIN_GROUP              = 12282; //You cannot join the group because % 1 is either link - dead or is not in this zone.
	const uint16 CAMP_ABANDON                   = 12290; //You abandon your preparations to camp.
	const uint16 WHOALL_AFK                     = 12311; //AFK
	const uint16 WHOALL_GM_FLAG                 = 12312; //* GM *
	const uint16 WHOALL_LD                      = 12313; //<LINKDEAD>
	const uint16 WHOALL_LFG                     = 12314; //LFG
	const uint16 WHOALL_TRADER                  = 12315; //TRADER
	const uint16 PC_SAVED                       = 12322; //%1 saved.
	const uint16 TALKING_TO_SELF                = 12323; //Talking to yourself again?
	const uint16 SPLIT_NO_GROUP	                = 12328; //You are not in a group!Keep it all.
	const uint16 NOT_IN_CONTROL                 = 12368; //You do not have control of yourself right now.
	const uint16 STEAL_FROM_SELF                = 12409; //You can't seem to steal from yourself for some reason...
	const uint16 STEAL_CORPSES                  = 12406; //You must target a player to steal from first.  You may not steal from corpses.
	const uint16 STEAL_PLAYERS                  = 12410; //You may not steal from a person who does not follow the ways of chaos....
	const uint16 STEAL_OUTSIDE_LEVEL            = 12413; //You can only steal from others in your level range.
	const uint16 TOO_DISTRACTED	                = 12440; //You are too distracted to cast a spell now!
	const uint16 MUST_BE_STANDING_TO_CAST       = 12441; //You must be standing to cast a spell.
	const uint16 ALREADY_CASTING                = 12442; //You are already casting a spell!
	const uint16 SHIMMERS_BRIEFLY               = 12444; //Your %1 shimmers briefly.
	const uint16 SENSE_CORPSE_NOT_NAME          = 12446; //You don't sense any corpses of that name.
	const uint16 SENSE_CORPSE_NONE              = 12447; //You don't sense any corpses.
	const uint16 SCREECH_BUFF_BLOCK             = 12448; //Your immunity buff protected you from the spell %1!
	const uint16 NOT_HOLDING_ITEM               = 12452; //You are not holding an item!
	const uint16 SENSE_UNDEAD                   = 12471; //You sense undead in this direction.
	const uint16 SENSE_ANIMAL                   = 12472; //You sense an animal in this direction.
	const uint16 SENSE_SUMMONED                 = 12473; //You sense a summoned being in this direction.
	const uint16 SENSE_NOTHING                  = 12474; //You don't sense anything.
	const uint16 SENSE_TRAP	                    = 12475; //You sense a trap in this direction.
	const uint16 DO_NOT_SENSE_TRAP              = 12476; //You don't sense any traps.
	const uint16 INTERRUPT_SPELL_OTHER          = 12478; //%1's casting is interrupted!
	const uint16 YOU_HIT_NONMELEE               = 12481; //You were hit by non-melee for %1 damage.
	const uint16 BEAM_SMILE                     = 12501; //%1 beams a smile at %2
	const uint16 TRACK_LOST_TARGET              = 12681; //You have lost your tracking target.
	const uint16 TRACK_STRAIGHT_AHEAD           = 12676;
	const uint16 TRACK_AHEAD_AND_TO             = 12677;
	const uint16 TRACK_TO_THE                   = 12678;
	const uint16 TRACK_BEHIND_AND_TO            = 12679;
	const uint16 TRACK_BEHIND_YOU               = 12680;
	const uint16 SONG_ENDS_ABRUPTLY             = 12686; //Your song ends abruptly.
	const uint16 SONG_ENDS                      = 12687; //Your song ends.
	const uint16 SONG_ENDS_OTHER                = 12688; //%1's song ends.
	const uint16 SONG_ENDS_ABRUPTLY_OTHER       = 12689; //%1's song ends abruptly.
	const uint16 DIVINE_AURA_NO_ATK             = 12695; //You can't attack while invulnerable!
	const uint16 TRY_ATTACKING_SOMEONE          = 12696; //Try attacking someone other than yourself, it's more productive.
	const uint16 BACKSTAB_WEAPON                = 12874; //You need a piercing weapon as your primary weapon in order to backstab
	const uint16 DROPPED_ITEM                   = 12904; //There was no room in your inventory, and the item has dropped to the ground.
	const uint16 MORE_SKILLED_THAN_I            = 12931; //%1 tells you, 'You are more skilled than I! What could I possibly teach you?'
	const uint16 SURNAME_EXISTS                 = 12939; //You already have a surname. Operation failed.
	const uint16 SURNAME_LEVEL                  = 12940; //You can only submit a surname upon reaching the 20th level. Operation failed.
	const uint16 SURNAME_TOO_LONG               = 12942; //Surname must be less than 20 characters in length.
	const uint16 REPORT_ONCE                    = 12945; //You may only submit a report once per time that you zone. Thank you.
	const uint16 NOW_INVISIBLE                  = 12950; //%1 is now Invisible.
	const uint16 NOW_VISIBLE                    = 12951; //%1 is now Visible.
	const uint16 GUILD_NOT_MEMBER2              = 12966; //You are not in a guild.
	const uint16 DISC_LEVEL_USE_ERROR           = 13004; //You are not sufficient level to use this discipline.
	const uint16 NO_CORPSES                     = 13048; //You don't have any corpses in this zone.
	const uint16 SPLIT_FAIL                     = 13112; //There is not enough to split, keep it.
	const uint16 TOGGLE_ON                      = 13172; //Asking server to turn ON your incoming tells.
	const uint16 TOGGLE_OFF                     = 13173; //Asking server to turn OFF all incoming tells for you.
	const uint16 DUEL_INPROGRESS                = 13251; //You have already accepted a duel with someone else cowardly dog.
	const uint16 GENERIC_MISS                   = 15041; //%1 missed %2
}

#endif

