// Generated by DumpStructTable.idc
Opcode _MAC_NET_MSG_approve:
 Name: name
  Type: char
 Name: race
  Type: int
 Name: cclass
  Type: int
 Name: sysop
  Type: char
 Name: status
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_applyPoison:
 Name: inven_location
  Type: int
 Name: success
  Type: int
  Type: void
Opcode _MAC_NET_MSG_anim_msg:
 Name: player_id
  Type: unsigned short
 Name: anim
  Type: int
 Name: anim_speed
  Type: float
  Type: void
Opcode _MAC_NET_MSG_AltTimerMsg:
 Name: time_last_used
  Type: int
 Name: ability
  Type: short
 Name: current_time
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_altGive:
 Name: target
  Type: unsigned short
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_AltexpUpMsg:
 Name: experience
  Type: unsigned long
 Name: ability_pts
  Type: short
 Name: alt
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_alternateMsg:
 Name: desc
  Type: char
  Type: void
Opcode _MAC_NET_MSG_AbilityMsg:
 Name: ability
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG___avLevel:
 Name: level
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_bzrItemUpdateMsg:
 Name: msg_type
  Type: short
 Name: item_id
  Type: int
 Name: ask_price
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_bzrSearchMsg:
 Name: msg_type
  Type: short
 Name: player_id
  Type: unsigned short
 Name: cclass
  Type: short
 Name: crace
  Type: short
 Name: stat
  Type: short
 Name: slot
  Type: short
 Name: type
  Type: short
 Name: item_name
  Type: char
 Name: iMinPrice
  Type: int
 Name: iMaxPrice
  Type: int
  Type: void
Opcode _MAC_NET_MSG_bzrItemArrayMsg:
 Name: msg_type
  Type: short
 Name: bzrItem
  Type: int
 Name: bzrPrice
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_bzrGenericMsg:
 Name: msg_type
  Type: short
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_bzrBuyMsg:
 Name: msg_type
  Type: short
 Name: bzr_merc_id
  Type: unsigned short
 Name: item_id
  Type: int
 Name: ask_price
  Type: unsigned long
 Name: quantity
  Type: short
 Name: slot
  Type: short
 Name: item_name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_buffUp:
 Name: target
  Type: unsigned short
 Name: level
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_beginTrade:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_becomeNPCMsg:
  Type: unsigned short
 Name: level
  Type: int
  Type: void
Opcode _MAC_NET_MSG_BazaarMsgItem:
 Name: msg_type
  Type: short
 Name: qty
  Type: short
 Name: item_id
  Type: short
 Name: seller_id
  Type: unsigned short
 Name: price
  Type: unsigned int
 Name: item_name
  Type: char
  Type: void
Opcode _MAC_NET_MSG__bugrpt:
 Name: name
  Type: char
 Name: account
  Type: char
 Name: time
  Type: char
 Name: date
  Type: char
 Name: dupe
  Type: char
 Name: crash
  Type: char
 Name: text
  Type: char
  Type: void
Opcode _MAC_NET_MSG___bandage:
  Type: unsigned short
 Name: amt
  Type: short
  Type: void
Opcode _MAC_NET_MSG_createItem_MacMsg:
 Name: name
  Type: char
 Name: recordNbr
  Type: short
 Name: slot
  Type: short
  Type: void
Opcode _MAC_NET_MSG_createGuild:
 Name: guild_faction
  Type: int
 Name: guild_name
  Type: char
 Name: guild_leader
  Type: char
 Name: status
  Type: int
 Name: gm_name
  Type: char
 Name: worldServerOK
  Type: int
 Name: guild_id
  Type: unsigned int
  Type: void
Opcode _MAC_NET_MSG_createGold:
 Name: amt
  Type: int
  Type: void
Opcode _MAC_NET_MSG_corpseLogMsg:
 Name: name
  Type: char
 Name: logActive
  Type: int
  Type: void
Opcode _MAC_NET_MSG_controlNpc:
 Name: target
  Type: unsigned short
 Name: control
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_consentVerify:
 Name: looter
  Type: char
 Name: corpsename
  Type: char
 Name: consent
  Type: char
  Type: void
Opcode _MAC_NET_MSG_clrFaction:
 Name: name
  Type: char
 Name: factionnum
  Type: int
  Type: void
Opcode _MAC_NET_MSG_clientAddPlayer:
 Name: crc32
  Type: int
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_clientUseCharge:
 Name: inv_refnum
  Type: unsigned long
 Name: hunger
  Type: char
 Name: thirst
  Type: char
 Name: expend
  Type: char
  Type: void
Opcode _MAC_NET_MSG_client_spawn_npc:
 Name: name
  Type: char
 Name: filename
  Type: char
  Type: float
  Type: float
  Type: float
 Name: qty
  Type: unsigned char
 Name: duration
  Type: unsigned int
  Type: void
Opcode _MAC_NET_MSG_clearSlot:
 Name: merchant
  Type: unsigned short
  Type: unsigned short
 Name: slot
  Type: char
  Type: void
Opcode _MAC_NET_MSG_chngSkill:
 Name: target
  Type: unsigned short
 Name: skill
  Type: int
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_chngForm:
 Name: targetid
  Type: unsigned short
 Name: race
  Type: short
 Name: sex
  Type: unsigned char
 Name: texture_type
  Type: char
 Name: head
  Type: char
 Name: face
  Type: short
 Name: Hair
  Type: unsigned char
 Name: HairColor
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: height
  Type: int
  Type: void
Opcode _MAC_NET_MSG_chngName:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: newname
  Type: char
 Name: badName
  Type: unsigned short
 Name: changed
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_chestLock:
  Type: unsigned short
 Name: sernbr
  Type: unsigned long
 Name: status
  Type: short
 Name: type
  Type: short
 Name: capacity
  Type: int
 Name: image_nbr
  Type: int
  Type: void
Opcode _MAC_NET_MSG_changeWorldMsg:
 Name: state
  Type: ChangeWorld_State
 Name: status
  Type: ChangeWorld_State
 Name: origCharName
  Type: char
 Name: origWorldName
  Type: char
 Name: origZoneId
  Type: short
 Name: origAvaLevel
  Type: short
 Name: newCharName
  Type: char
 Name: newHostAddr
  Type: char
 Name: newPort
  Type: short
 Name: newZoneId
  Type: short
 Name: stationId
  Type: char
 Name: credentials
  Type: char
  Type: void
Opcode _MAC_NET_MSG_changeMoney:
 Name: name
  Type: char
 Name: type
  Type: int
 Name: qty
  Type: int
  Type: void
Opcode _MAC_NET_MSG_changeItem:
 Name: name
  Type: char
 Name: refnum
  Type: int
  Type: void
Opcode _MAC_NET_MSG_changeGuildLeader:
 Name: newLeader
  Type: char
  Type: void
Opcode _MAC_NET_MSG_chngAbility:
 Name: target
  Type: unsigned short
 Name: ability
  Type: int
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_castspellmsg:
 Name: which_slot
  Type: short
 Name: spell_nbr
  Type: short
 Name: item_slot
  Type: short
 Name: target_id
  Type: unsigned short
 Name: crc32
  Type: int
  Type: void
Opcode _MAC_NET_MSG_canTrade:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_cancelDuel:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
 Name: reason
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_duel:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_dopostMsg:
 Name: source
  Type: unsigned short
 Name: time
  Type: char
 Name: author
  Type: char
 Name: language
  Type: short
 Name: subject
  Type: char
 Name: type
  Type: short
  Type: void
Opcode _MAC_NET_MSG_doPlayer2:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: stationNum
  Type: char
 Name: found
  Type: char
 Name: dir
  Type: char
  Type: void
Opcode _MAC_NET_MSG_doPlayer:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: found
  Type: char
  Type: void
Opcode _MAC_NET_MSG_doNpcCmd:
  Type: unsigned short
 Name: index
  Type: short
  Type: void
Opcode _MAC_NET_MSG_doHouseMoney:
 Name: money
  Type: long
  Type: void
Opcode _MAC_NET_MSG_doHouseLock:
 Name: status
  Type: int
  Type: unsigned short
 Name: status
  Type: long
  Type: void
Opcode _MAC_NET_MSG_doCombine:
 Name: type
  Type: unsigned char
 Name: skill
  Type: short
 Name: location
  Type: short
 Name: item
  Type: short
 Name: product
  Type: short
 Name: difficulty
  Type: short
 Name: itemrefnum
  Type: short
  Type: void
Opcode _MAC_NET_MSG_disband:
 Name: target
  Type: char
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_disarmMsg:
 Name: source
  Type: unsigned short
 Name: target
  Type: unsigned short
 Name: skill
  Type: short
 Name: status
  Type: char
  Type: void
Opcode _MAC_NET_MSG_deleteMsg:
 Name: source
  Type: unsigned short
  Type: unsigned short
 Name: category
  Type: int
  Type: void
Opcode _MAC_NET_MSG_expUpMsg:
 Name: experience
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_expSet:
 Name: target
  Type: unsigned short
 Name: level
  Type: float
  Type: void
Opcode _MAC_NET_MSG_expGive:
 Name: target
  Type: unsigned short
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_expGain:
  Type: unsigned short
 Name: exp
  Type: int
  Type: void
Opcode _MAC_NET_MSG_expendItemCharge:
 Name: item_class
  Type: int
 Name: record_nbr
  Type: int
  Type: void
Opcode _MAC_NET_MSG_EQToggleSwitch:
  Type: unsigned char
 Name: picking_skill
  Type: short
 Name: record_nbr
  Type: short
 Name: player_id
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_EQSwitchState:
  Type: unsigned char
 Name: state
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_EQSuccessfulHit:
 Name: defender_id
  Type: unsigned short
 Name: attacker_id
  Type: unsigned short
 Name: skill_used
  Type: unsigned char
 Name: spell_nbr
  Type: short
 Name: damage_done
  Type: int
 Name: force
  Type: float
 Name: hit_heading
  Type: float
 Name: hit_pitch
  Type: float
  Type: void
Opcode _MAC_NET_MSG_EQPlayerDeath:
 Name: victim_id
  Type: unsigned short
 Name: killer_id
  Type: unsigned short
 Name: corpse_number
  Type: unsigned short
 Name: victim_level
  Type: unsigned char
 Name: spell_nbr
  Type: short
 Name: skill_used
  Type: unsigned char
 Name: damage_done
  Type: int
 Name: is_PC
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_EQPlayer:
 Name: type
  Type: unsigned char
 Name: name
  Type: char
 Name: zone_id
  Type: EQZoneIndex
 Name: myphysics
  Type: physicsinfo
 Name: prev
  Type: EQPlayer *
 Name: next
  Type: EQPlayer *
 Name: corpse
  Type: void *
 Name: LocalInfo
  Type: EQPMInfo *
 Name: My_Char
  Type: void *
 Name: view_height
  Type: float
 Name: sprite_oheight
  Type: float
  Type: unsigned short
 Name: leader_id
  Type: unsigned short
 Name: max_hp
  Type: int
 Name: cur_hp
  Type: int
 Name: guild
  Type: short
 Name: my_socket
  Type: connection_t **
 Name: NPC
  Type: unsigned char
 Name: cclass
  Type: unsigned char
 Name: crace
  Type: unsigned short
 Name: csex
  Type: unsigned char
 Name: clevel
  Type: unsigned char
 Name: is_invis
  Type: unsigned char
 Name: is_sneaking
  Type: unsigned char
 Name: pkill
  Type: unsigned char
 Name: position
  Type: unsigned char
 Name: light
  Type: unsigned char
 Name: face
  Type: unsigned char
 Name: armor_type
  Type: unsigned short
 Name: tint
  Type: unsigned long
 Name: texture_type
  Type: char
 Name: height
  Type: float
 Name: width
  Type: float
 Name: length
  Type: float
 Name: head_type
  Type: char
 Name: walk_speed
  Type: float
 Name: run_speed
  Type: float
 Name: zonecontrol
  Type: char
  Type: char
 Name: nograv
  Type: short
 Name: bodytype
  Type: int
 Name: view_player
  Type: EQPlayer *
 Name: anonymous
  Type: int
 Name: avatar
  Type: short
 Name: afk
  Type: int
 Name: pc_summoned
  Type: int
 Name: title_nbr
  Type: int
 Name: extra
  Type: int
 Name: lastName
  Type: char
 Name: guild_status
  Type: short
 Name: deity
  Type: short
 Name: anim_variation
  Type: unsigned char
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: SerialNumber
  Type: EQSerialNumber
 Name: m_bTemporaryPet
  Type: char
  Type: void
Opcode _MAC_NET_MSG_EQObject:
 Name: type
  Type: unsigned char
 Name: prev
  Type: EQObject *
 Name: next
  Type: EQObject *
 Name: name
  Type: char
 Name: actor_tag
  Type: char
 Name: scale
  Type: float
  Type: float
  Type: float
  Type: float
  Type: float
  Type: float
 Name: my_actor
  Type: T3D_ACTORINSTANCEPTR
  Type: void
Opcode _MAC_NET_MSG_EQNetPlayer:
 Name: random_dontuse
  Type: unsigned int
 Name: netphysics
  Type: netphysicsinfo
 Name: leader_id
  Type: unsigned short
 Name: anim_variation
  Type: unsigned char
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: title_nbr
  Type: unsigned char
 Name: height
  Type: float
 Name: walk_speed
  Type: float
 Name: run_speed
  Type: float
 Name: tint
  Type: unsigned long
  Type: unsigned short
 Name: bodytype
  Type: short
 Name: hp_percentage
  Type: char
 Name: guild
  Type: short
 Name: crace
  Type: unsigned short
 Name: NPC
  Type: unsigned char
 Name: cclass
  Type: unsigned char
 Name: csex
  Type: unsigned char
 Name: clevel
  Type: unsigned char
 Name: is_invis
  Type: unsigned char
 Name: is_sneaking
  Type: unsigned char
 Name: pkill
  Type: unsigned char
 Name: position
  Type: unsigned char
 Name: light
  Type: unsigned char
 Name: anonymous
  Type: char
 Name: afk
  Type: char
 Name: pc_summoned
  Type: char
 Name: zonecontrol
  Type: char
  Type: char
 Name: nograv
  Type: char
 Name: texture_type
  Type: char
 Name: head_type
  Type: char
 Name: face
  Type: unsigned char
 Name: armor_type
  Type: unsigned short
 Name: guild_status
  Type: short
 Name: deity
  Type: short
 Name: temporaryPet
  Type: char
 Name: name
  Type: char
 Name: lastName
  Type: char
  Type: void
Opcode _MAC_NET_MSG_EQMoneyList:
 Name: prev
  Type: EQMoneyList *
 Name: next
  Type: EQMoneyList *
 Name: platinum
  Type: int
 Name: gold
  Type: int
 Name: silver
  Type: int
 Name: copper
  Type: int
 Name: serial_nbr
  Type: int
 Name: zone_name
  Type: char
 Name: expires
  Type: long
 Name: my_actor
  Type: T3D_ACTORINSTANCEPTR
  Type: float
  Type: float
  Type: float
 Name: heading
  Type: float
 Name: pitch
  Type: float
 Name: roll
  Type: float
 Name: actor_tag
  Type: char
  Type: void
Opcode _MAC_NET_MSG_EQMissileHitinfo:
 Name: defender_id
  Type: unsigned short
 Name: attacker_id
  Type: unsigned short
 Name: attack_rating
  Type: short
 Name: base_damage
  Type: int
 Name: force
  Type: float
 Name: hit_heading
  Type: float
 Name: hit_pitch
  Type: float
 Name: skill_used
  Type: unsigned char
 Name: min_damage
  Type: unsigned short
 Name: tohit
  Type: unsigned short
 Name: spell_nbr
  Type: short
 Name: spell_lvl
  Type: unsigned char
 Name: misc_info
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_EQMissile:
 Name: type
  Type: unsigned char
 Name: prev
  Type: EQMissile *
 Name: next
  Type: EQMissile *
 Name: myphysics
  Type: physicsinfo
 Name: LocalInfo
  Type: EQPMInfo *
 Name: launcher_id
  Type: unsigned short
 Name: target_id
  Type: unsigned short
 Name: record_nbr
  Type: short
 Name: attack_rating
  Type: short
 Name: base_damage
  Type: int
 Name: light
  Type: unsigned char
 Name: weight
  Type: unsigned char
 Name: range
  Type: unsigned char
 Name: wclass
  Type: unsigned char
 Name: skill_used
  Type: unsigned char
 Name: actor_tag
  Type: char
  Type: void
Opcode _MAC_NET_MSG_EQItemList:
 Name: prev
  Type: EQItemList *
 Name: next
  Type: EQItemList *
 Name: record_nbr
  Type: short
 Name: serial_nbr
  Type: long
 Name: zone_id
  Type: EQZoneIndex
 Name: my_actor
  Type: void *
 Name: affect
  Type: EQ_Affect
 Name: con_affects
  Type: EQ_Affect
 Name: expires
  Type: long
 Name: heading
  Type: float
  Type: float
  Type: float
  Type: float
 Name: actor_tag
  Type: char
 Name: items_held
  Type: short
 Name: zonefile_index
  Type: int
 Name: weight
  Type: int
 Name: key
  Type: short
 Name: locked
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_EQCVersionInfo:
  Type: VersionWord
  Type: void
Opcode _MAC_NET_MSG_EQClientSwitch:
 Name: actor_tag
  Type: char
 Name: beg_x
  Type: float
 Name: beg_y
  Type: float
 Name: beg_z
  Type: float
 Name: beg_h
  Type: float
 Name: beg_p
  Type: short
 Name: scale
  Type: short
 Name: player_id
  Type: unsigned short
  Type: unsigned char
 Name: type
  Type: unsigned char
 Name: state
  Type: unsigned char
 Name: beg_state
  Type: unsigned char
 Name: spell
  Type: short
  Type: void
Opcode _MAC_NET_MSG_eq_time:
 Name: cur_hour
  Type: unsigned char
 Name: cur_minute
  Type: unsigned char
 Name: cur_day
  Type: unsigned char
 Name: cur_month
  Type: unsigned char
 Name: cur_year
  Type: short
  Type: void
Opcode _MAC_NET_MSG_EQ_PCData4:
 Name: home_zone
  Type: EQZoneIndex
 Name: home_x
  Type: float
 Name: home_y
  Type: float
 Name: home_z
  Type: float
 Name: home_h
  Type: float
 Name: vault_affects
  Type: EQ_Affect
 Name: vault_con_affects
  Type: EQ_Affect
 Name: login_time
  Type: unsigned long
 Name: _vault
  Type: short
 Name: _vault_con
  Type: short
 Name: deity
  Type: short
 Name: guild
  Type: short
 Name: created
  Type: time_t
 Name: last_played
  Type: time_t
 Name: minutes_played
  Type: unsigned long
 Name: thirst
  Type: char
 Name: hunger
  Type: char
 Name: fatigue
  Type: char
 Name: pkill
  Type: unsigned char
 Name: highest_level
  Type: unsigned char
 Name: anonymous
  Type: unsigned char
  Type: unsigned char
 Name: guild_status
  Type: unsigned char
 Name: sobriety
  Type: short
 Name: spell_used
  Type: unsigned int
 Name: groupnames
  Type: char
 Name: groupdat
  Type: int
 Name: Post60Exp
  Type: unsigned int
 Name: NobilityRank
  Type: unsigned char
 Name: do_alt_exp
  Type: unsigned char
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: OldFace
  Type: unsigned char
 Name: NewArmorType
  Type: int
 Name: NewArmorTint
  Type: unsigned long
 Name: pcabilities
  Type: unsigned short
 Name: ATR_DIVINE_RES_timer
  Type: unsigned int
 Name: ATR_FREE_HOT_timer
  Type: unsigned int
 Name: ATR_TARGET_DA_timer
  Type: unsigned int
 Name: ATR_PURIFY_timer
  Type: unsigned int
 Name: ATR_DIRE_CHARM_timer
  Type: unsigned int
 Name: ATR_STRONG_ROOT_timer
  Type: unsigned int
 Name: ATR_MASOCHISM_timer
  Type: unsigned int
 Name: ATR_MANA_BURN_timer
  Type: unsigned int
 Name: ATR_GATHER_MANA_timer
  Type: unsigned int
 Name: ATR_PET_LOH_timer
  Type: unsigned int
 Name: ATR_DEADMEZ_timer
  Type: unsigned int
 Name: ATR_MASS_FEAR_timer
  Type: unsigned int
 Name: new_air_supply
  Type: short
 Name: AbilityPts
  Type: short
 Name: ATR_MASS_BUFF_timer
  Type: unsigned int
 Name: SerialNumber
  Type: DWORD
 Name: mBitFlags
  Type: unsigned char
 Name: POP_CLASS_SPELL_TIMER
  Type: unsigned int
 Name: m_tmLastShield
  Type: unsigned int
 Name: m_tmLastModulated
  Type: unsigned int
 Name: PCExtraInt
  Type: int
  Type: void
Opcode _MAC_NET_MSG_EQ_PCData3:
 Name: home_zone
  Type: EQZoneIndex
 Name: home_x
  Type: float
 Name: home_y
  Type: float
 Name: home_z
  Type: float
 Name: home_h
  Type: float
 Name: vault_affects
  Type: EQ_Affect
 Name: vault_con_affects
  Type: EQ_Affect
 Name: login_time
  Type: unsigned long
 Name: _vault
  Type: short
 Name: _vault_con
  Type: short
 Name: deity
  Type: short
 Name: guild
  Type: short
 Name: created
  Type: time_t
 Name: last_played
  Type: time_t
 Name: minutes_played
  Type: unsigned long
 Name: thirst
  Type: char
 Name: hunger
  Type: char
 Name: fatigue
  Type: char
 Name: pkill
  Type: unsigned char
 Name: highest_level
  Type: unsigned char
 Name: anonymous
  Type: unsigned char
  Type: unsigned char
 Name: guild_status
  Type: unsigned char
 Name: sobriety
  Type: short
 Name: spell_used
  Type: unsigned int
 Name: groupnames
  Type: char
 Name: groupdat
  Type: int
 Name: Post60Exp
  Type: unsigned int
 Name: NobilityRank
  Type: unsigned char
 Name: do_alt_exp
  Type: unsigned char
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: OldFace
  Type: unsigned char
 Name: NewArmorType
  Type: int
 Name: NewArmorTint
  Type: unsigned long
 Name: pcabilities
  Type: unsigned short
 Name: ATR_DIVINE_RES_timer
  Type: unsigned int
 Name: ATR_FREE_HOT_timer
  Type: unsigned int
 Name: ATR_TARGET_DA_timer
  Type: unsigned int
 Name: ATR_PURIFY_timer
  Type: unsigned int
 Name: ATR_DIRE_CHARM_timer
  Type: unsigned int
 Name: ATR_STRONG_ROOT_timer
  Type: unsigned int
 Name: ATR_MASOCHISM_timer
  Type: unsigned int
 Name: ATR_MANA_BURN_timer
  Type: unsigned int
 Name: ATR_GATHER_MANA_timer
  Type: unsigned int
 Name: ATR_PET_LOH_timer
  Type: unsigned int
 Name: ATR_DEADMEZ_timer
  Type: unsigned int
 Name: ATR_MASS_FEAR_timer
  Type: unsigned int
 Name: new_air_supply
  Type: short
 Name: AbilityPts
  Type: short
 Name: ATR_MASS_BUFF_timer
  Type: unsigned int
 Name: SerialNumber
  Type: DWORD
 Name: mBitFlags
  Type: unsigned char
 Name: POP_CLASS_SPELL_TIMER
  Type: unsigned int
 Name: PCExtraInt
  Type: int
  Type: void
Opcode _MAC_NET_MSG_EQ_PC:
 Name: Parent_Class
  Type: EQ_Character
 Name: Parent_Class
  Type: EQ_PCData4
 Name: vault
  Type: EQ_Item *
 Name: my_socket
  Type: connection_t *
 Name: GuarBuffer
  Type: char *
 Name: Buffer
  Type: char *
 Name: prev
  Type: EQ_PC *
 Name: next
  Type: EQ_PC *
 Name: TransfersReceived
  Type: uint32
 Name: lastBuffOut
  Type: unsigned long
 Name: lastGuarBuffOut
  Type: unsigned long
 Name: buffstart
  Type: unsigned short
 Name: buffend
  Type: unsigned short
 Name: gbuffstart
  Type: unsigned short
 Name: gbuffend
  Type: unsigned short
 Name: m_lastLanguageSpoken
  Type: int
 Name: m_raidId
  Type: int
  Type: void
Opcode _MAC_NET_MSG_EQ_Note:
 Name: Parent_Class
  Type: EQ_Item
 Name: notetype
  Type: unsigned char
 Name: status
  Type: unsigned char
 Name: language
  Type: char
 Name: text
  Type: char
  Type: void
Opcode _MAC_NET_MSG_EQ_Item:
 Name: name
  Type: char
 Name: loreName
  Type: char
 Name: actor_tag
  Type: char
 Name: weight
  Type: unsigned char
 Name: rentable
  Type: unsigned char
 Name: droppable
  Type: unsigned char
 Name: size
  Type: unsigned char
 Name: type
  Type: unsigned char
 Name: record_nbr
  Type: short
 Name: image_nbr
  Type: short
 Name: location
  Type: short
 Name: position
  Type: long
 Name: value
  Type: long
 Name: cur_x
  Type: float
 Name: cur_y
  Type: float
 Name: cur_z
  Type: float
 Name: heading
  Type: float
 Name: inv_refnum
  Type: unsigned long
 Name: log
  Type: short
 Name: loot_log
  Type: short
 Name: avatar_lvl
  Type: short
 Name: bottom_feed
  Type: short
 Name: poof_item
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_eq_exception:
 Name: oldNum
  Type: unsigned int
 Name: newNum
  Type: unsigned int
 Name: msg
  Type: unsigned int
 Name: decr_msg
  Type: long
 Name: decr_time
  Type: long
  Type: void
Opcode _MAC_NET_MSG_EQ_Equipment:
 Name: Parent_Class
  Type: EQ_Item
 Name: STR
  Type: char
 Name: STA
  Type: char
 Name: CHA
  Type: char
 Name: DEX
  Type: char
 Name: INT
  Type: char
 Name: AGI
  Type: char
 Name: WIS
  Type: char
 Name: save_magic
  Type: char
 Name: save_fire
  Type: char
 Name: save_cold
  Type: char
 Name: save_disease
  Type: char
 Name: save_poison
  Type: char
  Type: short
 Name: mana
  Type: short
  Type: short
 Name: maxCharges
  Type: char
 Name: burn
  Type: unsigned char
 Name: light
  Type: unsigned char
 Name: ticks
  Type: unsigned char
 Name: base_damage
  Type: unsigned char
 Name: activated
  Type: unsigned char
 Name: range
  Type: unsigned char
 Name: cclass
  Type: unsigned char
 Name: enchantable
  Type: unsigned char
 Name: spell_level
  Type: unsigned char
 Name: armor_type
  Type: unsigned char
 Name: tint
  Type: unsigned long
 Name: faction
  Type: short
 Name: spell_nbr
  Type: short
 Name: pclass
  Type: long
 Name: race
  Type: long
 Name: affect
  Type: EQ_Affect
 Name: merchant_gouge
  Type: float
 Name: extra_eqdat
  Type: int
 Name: recast_timer
  Type: long
 Name: spec_skill
  Type: unsigned char
 Name: spec_skill_percent
  Type: short
 Name: spec_race_bane
  Type: short
 Name: spec_bodytype_bane
  Type: short
 Name: spec_bane_damage
  Type: unsigned char
 Name: title_flag
  Type: short
 Name: level_restrict_stat
  Type: unsigned char
 Name: skill_restrict_stat
  Type: unsigned char
 Name: chance_proc
  Type: short
 Name: element_flag
  Type: unsigned char
 Name: element_dam
  Type: unsigned char
 Name: modfaction
  Type: short
 Name: modfaction_val
  Type: short
 Name: deity
  Type: long
 Name: hard_lvl_limit
  Type: short
 Name: instrument_type
  Type: short
 Name: instrument_mod
  Type: short
 Name: m_nFocusEffectNum
  Type: short
  Type: void
Opcode _MAC_NET_MSG_EQ_Container:
 Name: Parent_Class
  Type: EQ_Item
 Name: items_held
  Type: EQ_Item *
 Name: con_type
  Type: unsigned char
 Name: capacity
  Type: unsigned char
 Name: status
  Type: unsigned char
 Name: sizeMax
  Type: unsigned char
 Name: discount
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_EQ_CharacterData3:
 Name: version
  Type: EQCVersionInfo
 Name: name
  Type: char
 Name: lastName
  Type: char
 Name: Title
  Type: char
 Name: uniqueGuildID
  Type: unsigned int
 Name: sex
  Type: unsigned char
 Name: race
  Type: unsigned short
 Name: cclass
  Type: unsigned char
 Name: bodytype
  Type: unsigned short
 Name: level
  Type: unsigned char
 Name: experience
  Type: unsigned long
 Name: practices
  Type: short
 Name: cur_mana
  Type: short
 Name: cur_hp
  Type: short
 Name: status
  Type: char
 Name: STR
  Type: short
 Name: STA
  Type: short
 Name: CHA
  Type: short
 Name: DEX
  Type: short
 Name: INT
  Type: short
 Name: AGI
  Type: short
 Name: WIS
  Type: short
 Name: face
  Type: unsigned char
 Name: armor_type
  Type: unsigned char
 Name: tint
  Type: unsigned long
 Name: _possessions
  Type: short
 Name: languages
  Type: unsigned char
 Name: item_affects
  Type: EQ_Affect
 Name: m_Effects
  Type: EQ_Affect
 Name: _containers
  Type: short
 Name: con_affects
  Type: EQ_Affect
 Name: _spellbook
  Type: short
 Name: _memorized
  Type: short
 Name: _max_allowed_spell_slots
  Type: char
 Name: cur_x
  Type: float
 Name: cur_y
  Type: float
 Name: cur_z
  Type: float
 Name: heading
  Type: float
 Name: position
  Type: unsigned char
 Name: p_platinum
  Type: long
 Name: p_gold
  Type: long
 Name: p_silver
  Type: long
 Name: p_copper
  Type: long
 Name: b_platinum
  Type: long
 Name: b_gold
  Type: long
 Name: b_silver
  Type: long
 Name: b_copper
  Type: long
 Name: h_platinum
  Type: long
 Name: h_gold
  Type: long
 Name: h_silver
  Type: long
 Name: h_copper
  Type: long
 Name: a_platinum
  Type: long
 Name: a_gold
  Type: long
 Name: a_silver
  Type: long
 Name: a_copper
  Type: long
 Name: skill
  Type: short
 Name: innate
  Type: short
 Name: air_supply
  Type: char
 Name: texture_type
  Type: char
 Name: height
  Type: float
 Name: width
  Type: float
 Name: length
  Type: float
 Name: view_height
  Type: float
 Name: vehiclename
  Type: char
 Name: primActor
  Type: int
 Name: secdActor
  Type: int
 Name: extdatint
  Type: int
 Name: cur_zone_id
  Type: EQZoneIndex
  Type: void
Opcode _MAC_NET_MSG_EQ_Character:
 Name: Parent_Class
  Type: EQ_CharacterData3
  Type: EQPlayer *
 Name: possessions
  Type: EQ_Item *
 Name: spellcast_level
  Type: unsigned char
 Name: m_NpcEffects
  Type: EQ_Affect
 Name: m_EffectIds
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_EQ_Affect:
 Name: type
  Type: unsigned char
 Name: level
  Type: unsigned char
 Name: charges
  Type: unsigned char
 Name: activated
  Type: unsigned char
 Name: number
  Type: short
 Name: duration
  Type: short
 Name: data
  Type: short
  Type: void
Opcode _MAC_NET_MSG_endRt:
 Name: minx
  Type: long
 Name: miny
  Type: long
 Name: minz
  Type: long
 Name: maxx
  Type: long
 Name: maxy
  Type: long
 Name: maxz
  Type: long
  Type: void
Opcode _MAC_NET_MSG_emoteMsg:
 Name: lang_type
  Type: short
 Name: desc
  Type: char
  Type: void
Opcode _MAC_NET_MSG_fwaterMsg:
 Name: hunger
  Type: short
 Name: thirst
  Type: short
 Name: fatigue
  Type: short
  Type: void
Opcode _MAC_NET_MSG_forceTitle:
 Name: target
  Type: char
 Name: cmd
  Type: int
  Type: void
Opcode _MAC_NET_MSG_foodItem:
 Name: from
  Type: int
  Type: int
 Name: qty
  Type: int
 Name: foodwater
  Type: int
  Type: void
Opcode _MAC_NET_MSG_follow:
 Name: target
  Type: char
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_feignMsg:
  Type: unsigned short
 Name: fake
  Type: unsigned short
 Name: status
  Type: char
  Type: void
Opcode _MAC_NET_MSG_faction_MacMsg:
 Name: faction
  Type: short
 Name: name
  Type: char
 Name: standing
  Type: char
  Type: void
Opcode _MAC_NET_MSG_guildWar:
 Name: Parent_Class
  Type: guildPeace
  Type: void
Opcode _MAC_NET_MSG_guildStatus:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: guild
  Type: short
 Name: level
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildReply:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: status
  Type: int
 Name: guild
  Type: short
  Type: void
Opcode _MAC_NET_MSG_guildRename:
 Name: newGuildName
  Type: char
 Name: oldGuildName
  Type: char
  Type: void
Opcode _MAC_NET_MSG_guildRemove:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: guild
  Type: short
 Name: level
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildPeace:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: warWith
  Type: int
 Name: days
  Type: int
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildNameEntry:
 Name: name
  Type: char
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildmotdSet:
 Name: name
  Type: char
 Name: guild
  Type: int
 Name: message
  Type: char
  Type: void
Opcode _MAC_NET_MSG_guildList:
 Name: numrecs
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildInvite:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: guild
  Type: short
 Name: level
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildInfo:
 Name: num
  Type: int
 Name: name
  Type: guild_dat
  Type: void
Opcode _MAC_NET_MSG_guildExists:
 Name: guild
  Type: int
 Name: exists
  Type: int
  Type: void
Opcode _MAC_NET_MSG_guildCRCmsg:
 Name: crc32
  Type: int
 Name: gData
  Type: guild_dat
  Type: void
Opcode _MAC_NET_MSG_guildAdded:
 Name: guild_index
  Type: int
 Name: guild_entry
  Type: guild_dat
  Type: void
Opcode _MAC_NET_MSG_guild_dat:
 Name: faction_num
  Type: int
 Name: name
  Type: char
 Name: warguild
  Type: int
 Name: active
  Type: int
 Name: endWardate
  Type: unsigned long
 Name: warRequest
  Type: int
 Name: extdat1
  Type: int
 Name: extdat2
  Type: int
 Name: guildId
  Type: int
  Type: void
Opcode _MAC_NET_MSG_gmQuest:
 Name: target
  Type: unsigned short
 Name: experience
  Type: int
 Name: item
  Type: int
 Name: plat
  Type: int
 Name: gold
  Type: int
 Name: silv
  Type: int
 Name: copp
  Type: int
  Type: void
Opcode _MAC_NET_MSG_getStats:
 Name: name
  Type: char
 Name: level
  Type: short
 Name: cclass
  Type: short
 Name: skill
  Type: short
  Type: void
Opcode _MAC_NET_MSG_hpChgMsg:
  Type: unsigned short
 Name: cur_hp
  Type: int
  Type: void
Opcode _MAC_NET_MSG_hitptMsg:
  Type: unsigned short
  Type: int
 Name: max_hp
  Type: int
  Type: void
Opcode _MAC_NET_MSG_item_find_message:
 Name: itemNumber
  Type: int
 Name: partialName
  Type: char
  Type: void
Opcode _MAC_NET_MSG_invite:
 Name: target
  Type: char
 Name: name
  Type: char
 Name: party
  Type: char
 Name: pkill
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_InspectItem:
 Name: item_id
  Type: short
 Name: item_name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_inspect:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
 Name: name
  Type: char
 Name: image
  Type: short
 Name: text
  Type: char
 Name: title
  Type: char
  Type: void
Opcode _MAC_NET_MSG_joinStatus:
 Name: target
  Type: char
 Name: name
  Type: char
 Name: answer
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_kunarkMsg:
 Name: name
  Type: char
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_KunarkApprovedMsg:
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_keynumMsg:
 Name: keynum
  Type: int
 Name: recnum
  Type: short
 Name: rent
  Type: int
  Type: void
Opcode _MAC_NET_MSG_loot_msg:
 Name: target
  Type: unsigned short
  Type: unsigned short
 Name: slot
  Type: short
 Name: autoInven
  Type: int
  Type: void
Opcode _MAC_NET_MSG_logshoweq:
 Name: value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_LoginMsg:
 Name: unistring
  Type: char
 Name: port
  Type: short
 Name: zone_server
  Type: unsigned char
 Name: lreason
  Type: int
 Name: version
  Type: short
  Type: void
Opcode _MAC_NET_MSG_loginKey:
 Name: name
  Type: char
 Name: pword
  Type: char
 Name: keycode
  Type: char
 Name: hostname
  Type: char
 Name: port
  Type: short
  Type: void
Opcode _MAC_NET_MSG_lockmsg:
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_LFGMsg2:
  Type: unsigned short
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_LFGMsg:
 Name: name
  Type: unsigned char
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_levelUpMsg:
 Name: level
  Type: int
 Name: highestlevel
  Type: int
 Name: experience
  Type: int
  Type: void
Opcode _MAC_NET_MSG_leave_merchant:
 Name: merchant
  Type: unsigned short
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_leave_guildmaster:
 Name: guildmaster
  Type: unsigned short
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_launchSpellInfo:
 Name: slot
  Type: int
 Name: spell
  Type: int
 Name: type
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgTraceLogin:
 Name: stationNum
  Type: char
 Name: characterName
  Type: char
  Type: void
Opcode _MAC_NET_MSG_msgTeleportPC:
 Name: zoneid
  Type: EQZoneIndex
  Type: float
  Type: float
  Type: float
 Name: hdg
  Type: float
 Name: reason
  Type: ZONE_REQ_REASON
  Type: void
Opcode _MAC_NET_MSG_msgSkillImprove:
 Name: skillnum
  Type: int
 Name: skillvalue
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgQueryExp:
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_msgLimboMoney:
 Name: plat
  Type: long
 Name: gold
  Type: long
 Name: silver
  Type: long
 Name: copper
  Type: long
  Type: void
Opcode _MAC_NET_MSG_msgGiveitem:
 Name: source
  Type: char
 Name: tgt
  Type: char
 Name: type
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgGetSafeCoords:
 Name: name
  Type: char
 Name: zoneid
  Type: EQZoneIndex
  Type: float
  Type: float
  Type: float
 Name: hdg
  Type: float
 Name: status
  Type: ZONE_REQ_STATUS
  Type: void
Opcode _MAC_NET_MSG_MsgPetInfo:
 Name: Owner_ID
  Type: unsigned short
 Name: Pet_ID
  Type: unsigned short
 Name: flag
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_msgNpcReaction:
  Type: unsigned short
 Name: npcid
  Type: unsigned short
 Name: reaction
  Type: int
 Name: level
  Type: int
 Name: cur_hp
  Type: int
 Name: max_hp
  Type: int
 Name: server_type
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgDoAttack:
  Type: unsigned short
 Name: slot
  Type: int
 Name: skill
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgCorpseXYZ:
  Type: unsigned short
  Type: float
  Type: float
  Type: float
  Type: void
Opcode _MAC_NET_MSG_msgCompData:
 Name: num_items
  Type: short
 Name: compData
  Type: char
  Type: void
Opcode _MAC_NET_MSG_msgChangePCAffect:
  Type: unsigned short
 Name: affect
  Type: EQ_Affect
 Name: slot
  Type: int
 Name: change_type
  Type: int
  Type: void
Opcode _MAC_NET_MSG_msgAddPlayer:
 Name: crc32
  Type: int
 Name: playerdata
  Type: EQPlayer
  Type: void
Opcode _MAC_NET_MSG_msg_who_req:
 Name: name
  Type: char
 Name: race
  Type: short
 Name: cclass
  Type: short
 Name: lolvl
  Type: short
 Name: hilvl
  Type: short
  Type: short
 Name: guild
  Type: short
 Name: req_name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_msg_ppoint:
 Name: name
  Type: char
  Type: float
  Type: float
  Type: float
  Type: void
Opcode _MAC_NET_MSG_msg_delIlist:
 Name: sernbr
  Type: unsigned long
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_moveMoney:
 Name: from
  Type: int
  Type: int
 Name: typeFrom
  Type: int
 Name: typeTo
  Type: int
 Name: amt
  Type: int
  Type: void
Opcode _MAC_NET_MSG_moveItem:
 Name: from
  Type: int
  Type: int
 Name: qty
  Type: int
  Type: void
Opcode _MAC_NET_MSG_motdSet:
 Name: name
  Type: char
 Name: message
  Type: char
  Type: void
Opcode _MAC_NET_MSG_money_MacMsg:
 Name: name
  Type: char
 Name: platinum
  Type: long
 Name: gold
  Type: long
 Name: silver
  Type: long
 Name: copper
  Type: long
  Type: void
Opcode _MAC_NET_MSG_ModulationMsg:
 Name: fTimeLeft
  Type: unsigned int
  Type: void
Opcode _MAC_NET_MSG_modRt:
 Name: route
  Type: short
 Name: terrain
  Type: char
 Name: outdoor
  Type: BOOL
 Name: open
  Type: BOOL
 Name: height
  Type: char
 Name: minx
  Type: long
 Name: miny
  Type: long
 Name: minz
  Type: long
 Name: maxx
  Type: long
 Name: maxy
  Type: long
 Name: maxz
  Type: long
  Type: void
Opcode _MAC_NET_MSG_modMoney:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: type
  Type: unsigned char
 Name: amount
  Type: long
  Type: void
Opcode _MAC_NET_MSG_modInven:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: index
  Type: short
 Name: type
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_memSpellBook:
 Name: slot
  Type: int
 Name: spell
  Type: int
 Name: type
  Type: int
 Name: tempspellbook
  Type: short
  Type: void
Opcode _MAC_NET_MSG_meditateMsg:
 Name: meditating
  Type: int
  Type: void
Opcode _MAC_NET_MSG_materialChange:
  Type: unsigned short
 Name: location
  Type: unsigned char
 Name: type
  Type: unsigned short
 Name: tint
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_ManaMsg:
 Name: player_id
  Type: unsigned short
 Name: my_mana
  Type: short
  Type: void
Opcode _MAC_NET_MSG_makeNewLeaderMsg:
 Name: guild_faction
  Type: int
 Name: new_leader
  Type: char
  Type: void
Opcode _MAC_NET_MSG_NPCMoney:
 Name: sendId
  Type: unsigned short
 Name: targetId
  Type: unsigned short
 Name: platinum
  Type: long
 Name: gold
  Type: long
 Name: silver
  Type: long
 Name: copper
  Type: long
  Type: void
Opcode _MAC_NET_MSG_npcCheckItemsZone:
 Name: cmd
  Type: int
 Name: szFilter
  Type: char
  Type: void
Opcode _MAC_NET_MSG_npcCheckItems:
  Type: unsigned short
 Name: plat
  Type: int
 Name: gold
  Type: int
 Name: silver
  Type: int
 Name: copper
  Type: int
 Name: item_refnums
  Type: short
 Name: item_names
  Type: char
  Type: void
Opcode _MAC_NET_MSG_NoNameApprovalMsg:
 Name: name
  Type: char
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_netphysicsinfo:
 Name: accel
  Type: char
 Name: h
  Type: unsigned char
 Name: rate_h
  Type: char
 Name: x_pos
  Type: short
 Name: y_pos
  Type: short
 Name: z_pos
  Type: short
 Name: velocities
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_newtext:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: lang
  Type: short
 Name: type
  Type: short
 Name: locale
  Type: unsigned char
 Name: speakingskill
  Type: short
  Type: void
Opcode _MAC_NET_MSG_newSurname:
 Name: name
  Type: char
 Name: status
  Type: int
 Name: lastName
  Type: char
  Type: void
Opcode _MAC_NET_MSG_old_guild_dat:
 Name: faction_num
  Type: int
 Name: name
  Type: char
 Name: leader
  Type: char
 Name: numinzone
  Type: int
 Name: warguild
  Type: int
 Name: active
  Type: int
 Name: endWardate
  Type: unsigned long
 Name: warRequest
  Type: int
 Name: extdat1
  Type: int
 Name: extdat2
  Type: int
 Name: extstr
  Type: char
  Type: void
Opcode _MAC_NET_MSG_OverrideTimerMessage:
 Name: override_timer
  Type: int
  Type: void
Opcode _MAC_NET_MSG_publicKeyMsg:
  Type: vlMsg
  Type: void
Opcode _MAC_NET_MSG_prohibExe:
 Name: num
  Type: short
  Type: void
Opcode _MAC_NET_MSG_PINFO:
 Name: name
  Type: char
 Name: level
  Type: unsigned char
 Name: cclass
  Type: unsigned char
 Name: race
  Type: unsigned short
 Name: cur_zone_id
  Type: int
 Name: sex
  Type: unsigned char
 Name: face
  Type: unsigned char
 Name: type
  Type: int
 Name: tint
  Type: unsigned long
 Name: deity
  Type: short
 Name: primActor
  Type: int
 Name: secdActor
  Type: int
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_physicsinfo:
  Type: float
  Type: float
  Type: float
  Type: float
  Type: float
 Name: accel
  Type: float
  Type: float
  Type: float
  Type: float
 Name: rate_h
  Type: float
 Name: rate_p
  Type: float
 Name: view_pitch
  Type: float
  Type: void
Opcode _MAC_NET_MSG_petitionQtype:
 Name: id_num
  Type: int
 Name: urgency
  Type: int
 Name: user_handle
  Type: char
 Name: guide_handle
  Type: char
 Name: zoneid
  Type: int
 Name: char_name
  Type: char
 Name: level
  Type: int
 Name: cclass
  Type: int
 Name: race
  Type: int
 Name: cur_state
  Type: int
 Name: num_checkouts
  Type: int
 Name: unavailable
  Type: int
 Name: time_in
  Type: unsigned long
 Name: last_checkin_time
  Type: unsigned long
 Name: user_text
  Type: char
  Type: void
Opcode _MAC_NET_MSG_petitionQstatus:
 Name: id_num
  Type: int
 Name: urgency
  Type: int
 Name: cur_state
  Type: int
 Name: time_in
  Type: unsigned long
 Name: user_handle
  Type: char
 Name: dest_pc
  Type: char
 Name: num_active
  Type: int
 Name: pet_pc
  Type: char
 Name: last_checkin_time
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_pet_command_message:
 Name: command
  Type: PetCommandType
 Name: targetId
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_permaKillMsg:
  Type: unsigned short
 Name: delfile
  Type: int
  Type: void
Opcode _MAC_NET_MSG_PCSaveMsg:
 Name: crc32
  Type: int
 Name: pcdata
  Type: EQ_PC
 Name: SaveIndex
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_pcGuildMsg:
 Name: guild
  Type: int
 Name: status
  Type: int
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_rpServer:
 Name: rp_active
  Type: int
 Name: pk_active
  Type: int
 Name: AutoIdentify
  Type: int
 Name: NameGen
  Type: int
 Name: Gibberish
  Type: int
 Name: test_server
  Type: int
 Name: Locale
  Type: int
 Name: ProfanityFilter
  Type: int
 Name: ServerName
  Type: char
 Name: loggingServerPassword
  Type: char
 Name: loggingServerAddress
  Type: char
 Name: loggingServerPort
  Type: int
 Name: localizedEmailAddress
  Type: char
  Type: void
Opcode _MAC_NET_MSG_reward_MacMsg:
 Name: sendId
  Type: unsigned short
 Name: targetId
  Type: unsigned short
 Name: exp_reward
  Type: int
 Name: faction
  Type: int
 Name: faction_mod
  Type: int
 Name: copper
  Type: int
 Name: silver
  Type: int
 Name: gold
  Type: int
 Name: platinum
  Type: int
 Name: items
  Type: short
  Type: void
Opcode _MAC_NET_MSG_retHouseMoney:
  Type: unsigned short
 Name: sernbr
  Type: long
 Name: type
  Type: int
 Name: qty
  Type: int
  Type: void
Opcode _MAC_NET_MSG_retHouseItem:
  Type: unsigned short
 Name: sernbr
  Type: long
 Name: affect
  Type: EQ_Affect
 Name: recnum
  Type: short
 Name: slot
  Type: short
 Name: type
  Type: short
 Name: value
  Type: long
  Type: void
Opcode _MAC_NET_MSG_resurrectMsg:
  Type: unsigned short
 Name: zoneid
  Type: int
  Type: float
  Type: float
  Type: float
 Name: percentback
  Type: int
 Name: name
  Type: char
 Name: explost
  Type: unsigned long
 Name: caster
  Type: char
 Name: spellnum
  Type: short
 Name: corpsename
  Type: char
 Name: consent
  Type: int
  Type: void
Opcode _MAC_NET_MSG_rescue:
 Name: target
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_requestMsg:
 Name: source
  Type: unsigned short
  Type: unsigned short
 Name: type
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_requestHdr:
 Name: source
  Type: unsigned short
 Name: type
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_reqplayed:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: created
  Type: unsigned int
 Name: minutes_played
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_reqLootermsg:
 Name: requestor
  Type: unsigned char
 Name: corpse
  Type: unsigned char
 Name: looter
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_reqInsp:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_reqGuildName:
 Name: guild_faction
  Type: int
  Type: void
Opcode _MAC_NET_MSG_reqGuildChestLock:
  Type: unsigned short
 Name: key
  Type: short
 Name: data
  Type: short
  Type: void
Opcode _MAC_NET_MSG_req_guildmaster:
 Name: guildmaster
  Type: unsigned short
  Type: unsigned short
 Name: skill
  Type: short
 Name: greed
  Type: float
  Type: unsigned char
 Name: lang
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_req_merchant:
 Name: merchant
  Type: unsigned short
  Type: unsigned short
  Type: unsigned char
 Name: greed
  Type: float
  Type: void
Opcode _MAC_NET_MSG_req_bzr_merchant:
 Name: bzr_merc_id
  Type: unsigned short
 Name: item_id
  Type: int
 Name: bzr_greed
  Type: float
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_reportText:
 Name: name
  Type: char
 Name: buffer
  Type: char
 Name: offender
  Type: char
  Type: void
Opcode _MAC_NET_MSG_refuseTrade:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
 Name: reason
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_ranReturnMsg:
 Name: from
  Type: int
  Type: int
 Name: result
  Type: int
 Name: name
  Type: char
  Type: void
Opcode _MAC_NET_MSG_randomMsg:
 Name: from
  Type: int
  Type: int
  Type: void
Opcode _MAC_NET_MSG__readyTrade:
  Type: unsigned short
 Name: flag
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_switchSpell:
 Name: switch_id
  Type: int
 Name: spellnum
  Type: int
  Type: void
Opcode _MAC_NET_MSG_switchName:
 Name: name
  Type: char
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_swapSpell:
 Name: from
  Type: int
  Type: int
  Type: void
Opcode _MAC_NET_MSG_submit:
 Name: name
  Type: char
 Name: race
  Type: int
 Name: cclass
  Type: int
 Name: deity
  Type: int
  Type: void
Opcode _MAC_NET_MSG_stopcastingmsg:
 Name: cur_mana
  Type: short
 Name: spell_nbr
  Type: short
  Type: void
Opcode _MAC_NET_MSG_stell:
 Name: whom
  Type: char
 Name: tline
  Type: char
 Name: speaker
  Type: char
 Name: language
  Type: short
 Name: speakingskill
  Type: short
  Type: void
Opcode _MAC_NET_MSG_stealMsg:
 Name: target
  Type: unsigned short
 Name: source
  Type: unsigned short
 Name: skill
  Type: short
 Name: status
  Type: char
 Name: money
  Type: long
 Name: data
  Type: char
  Type: void
Opcode _MAC_NET_MSG_statUpdate:
  Type: unsigned short
 Name: physics
  Type: netphysicsinfo
  Type: void
Opcode _MAC_NET_MSG_statChange:
  Type: unsigned short
 Name: field
  Type: short
 Name: value
  Type: long
  Type: void
Opcode _MAC_NET_MSG_startRt:
 Name: terrain
  Type: char
 Name: outdoor
  Type: BOOL
 Name: open
  Type: BOOL
 Name: height
  Type: char
  Type: void
Opcode _MAC_NET_MSG_start_casting:
 Name: caster_id
  Type: unsigned short
 Name: spell_nbr
  Type: short
 Name: casting_time
  Type: unsigned int
  Type: void
Opcode _MAC_NET_MSG_soundMsg:
  Type: unsigned short
 Name: soundnum
  Type: short
  Type: void
Opcode _MAC_NET_MSG_soulMarkReqMsg:
 Name: gmName
  Type: char
 Name: gmstationNum
  Type: char
 Name: name
  Type: char
 Name: stationNum
  Type: char
  Type: void
Opcode _MAC_NET_MSG_soulMarkMsg:
 Name: name
  Type: char
 Name: soulMarks
  Type: sMark
  Type: void
Opcode _MAC_NET_MSG_soulMarkAddMsg:
 Name: soulMark
  Type: sMark
  Type: void
Opcode _MAC_NET_MSG_SpellWornOffMessage:
 Name: iID
  Type: short
 Name: iSpellNumber
  Type: short
  Type: void
Opcode _MAC_NET_MSG_argumentText:
 Name: source
  Type: unsigned short
 Name: token
  Type: int
  Type: void
Opcode _MAC_NET_MSG_spellText:
 Name: source
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_SpellActivateParticles:
 Name: iID
  Type: short
 Name: iSpellNumber
  Type: short
  Type: void
Opcode _MAC_NET_MSG_sp_chksum:
 Name: cksum
  Type: int
 Name: size
  Type: unsigned long
 Name: wordnum
  Type: unsigned long
 Name: wordval
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_snooptext:
 Name: snooper
  Type: char
 Name: target
  Type: char
 Name: source
  Type: char
 Name: type
  Type: short
  Type: void
Opcode _MAC_NET_MSG_sMark:
 Name: Name
  Type: char
 Name: stationNum
  Type: char
 Name: gmName
  Type: char
 Name: gmstationNum
  Type: char
 Name: timeStamp
  Type: unsigned long
 Name: category
  Type: int
 Name: text
  Type: char
  Type: void
Opcode _MAC_NET_MSG_SkillTmrMsg:
 Name: theSkill
  Type: short
 Name: theTimer
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_sisaLogMsg:
 Name: name
  Type: char
 Name: logActive
  Type: int
  Type: void
Opcode _MAC_NET_MSG_shieldMsg:
 Name: target
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_setFaction:
 Name: name
  Type: char
 Name: factionnum
  Type: int
 Name: fact_value
  Type: int
  Type: void
Opcode _MAC_NET_MSG_setDatRateMsg:
 Name: datarate
  Type: float
  Type: void
Opcode _MAC_NET_MSG_SendInspectItem:
 Name: data
  Type: char
  Type: void
Opcode _MAC_NET_MSG_sendHdr:
  Type: unsigned short
 Name: time
  Type: char
 Name: author
  Type: char
 Name: language
  Type: short
 Name: subject
  Type: char
  Type: void
Opcode _MAC_NET_MSG_send_eq2:
 Name: ask_price
  Type: unsigned long
 Name: location
  Type: int
  Type: unsigned short
 Name: type
  Type: char
  Type: void
Opcode _MAC_NET_MSG_send_eq:
  Type: unsigned short
 Name: type
  Type: char
  Type: void
Opcode _MAC_NET_MSG_sell_msg:
 Name: merchant
  Type: unsigned short
  Type: unsigned short
 Name: slot
  Type: short
 Name: quantity
  Type: int
 Name: value
  Type: long
  Type: void
Opcode _MAC_NET_MSG_searchCorpse:
 Name: name
  Type: char
 Name: corpsename
  Type: char
 Name: zoneid
  Type: int
  Type: void
Opcode _MAC_NET_MSG_sacrificeMsg:
 Name: necroID
  Type: int
 Name: playerID
  Type: int
 Name: response
  Type: int
  Type: void
Opcode _MAC_NET_MSG_tuneMsg:
  Type: unsigned short
 Name: bPersist
  Type: unsigned char
 Name: szParam
  Type: char
 Name: szArg
  Type: char
  Type: void
Opcode _MAC_NET_MSG_trapLocation:
  Type: float
  Type: float
  Type: float
  Type: void
Opcode _MAC_NET_MSG_translocateMsg:
 Name: zoneid
  Type: EQZoneIndex
 Name: trans_spell
  Type: int
 Name: response
  Type: int
 Name: caster
  Type: char
 Name: dest_x
  Type: float
 Name: dest_y
  Type: float
 Name: dest_z
  Type: float
 Name: is_ok
  Type: int
  Type: void
Opcode _MAC_NET_MSG_trainMsg:
 Name: gMasterId
  Type: unsigned short
 Name: language
  Type: int
 Name: skill
  Type: int
  Type: void
Opcode _MAC_NET_MSG_trademoney:
  Type: unsigned short
 Name: type
  Type: unsigned char
 Name: amt
  Type: long
  Type: void
Opcode _MAC_NET_MSG_tradeitem:
  Type: unsigned short
 Name: slot
  Type: short
 Name: type
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_tokenStringMsg:
 Name: string_token
  Type: short
 Name: string_color
  Type: short
 Name: fromWorld
  Type: short
  Type: void
Opcode _MAC_NET_MSG_toggleState:
 Name: state
  Type: int
  Type: void
Opcode _MAC_NET_MSG_tp_msg:
 Name: num_coords
  Type: short
  Type: tp_coords
  Type: void
Opcode _MAC_NET_MSG_tp_coords:
 Name: index
  Type: short
  Type: float
  Type: float
  Type: float
 Name: hdg
  Type: float
 Name: zoneid
  Type: int
  Type: void
Opcode _MAC_NET_MSG_tgtIDmsg:
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_tellToggle:
 Name: name
  Type: char
  Type: int
  Type: void
Opcode _MAC_NET_MSG_targetMsg:
 Name: target
  Type: unsigned short
  Type: void
Opcode _MAC_NET_MSG_TargetGroupBuffMsg:
 Name: iValue
  Type: int
  Type: void
Opcode _MAC_NET_MSG_updateFaceMsg:
 Name: HairColor
  Type: unsigned char
 Name: BeardColor
  Type: unsigned char
 Name: LeftEye
  Type: unsigned char
 Name: RightEye
  Type: unsigned char
 Name: Hair
  Type: unsigned char
 Name: Beard
  Type: unsigned char
 Name: face
  Type: unsigned char
  Type: void
Opcode _MAC_NET_MSG_updateFilters:
 Name: dmgshields
  Type: int
 Name: npcspells
  Type: int
 Name: pcspells
  Type: int
 Name: bardsongs
  Type: int
 Name: server_filter
  Type: int
 Name: guild_chat
  Type: int
 Name: socials
  Type: int
 Name: group_chat
  Type: int
 Name: shouts
  Type: int
 Name: auctions
  Type: int
 Name: oocs
  Type: int
 Name: my_misses
  Type: int
 Name: other_miss
  Type: int
 Name: other_hit
  Type: int
 Name: atk_miss_me
  Type: int
 Name: criticalspells
  Type: int
 Name: criticalmelee
  Type: int
  Type: void
Opcode _MAC_NET_MSG_vlMsg:
 Name: negative
  Type: int
 Name: share
  Type: int
 Name: array
  Type: int
  Type: int
  Type: int
  Type: void
Opcode _MAC_NET_MSG_VersionWord:
 Name: minor
  Type: BYTE
 Name: major
  Type: BYTE
  Type: void
Opcode _MAC_NET_MSG_vehicle_xfr:
 Name: vehicle
  Type: char
 Name: zoneid
  Type: EQZoneIndex
  Type: void
Opcode _MAC_NET_MSG_ww_MacMsg:
 Name: iflock
  Type: unsigned char
 Name: platinum
  Type: long
 Name: gold
  Type: long
 Name: silver
  Type: long
 Name: copper
  Type: long
  Type: void
Opcode _MAC_NET_MSG_WorldRemoveGuild:
 Name: source
  Type: char
 Name: target
  Type: char
 Name: szoneid
  Type: int
 Name: tzoneid
  Type: int
 Name: guild
  Type: int
 Name: level
  Type: int
 Name: status
  Type: int
  Type: void
Opcode _MAC_NET_MSG_wldgroupMsg:
 Name: cmd
  Type: int
 Name: name
  Type: char
 Name: member
  Type: char
 Name: strToken
  Type: unsigned long
  Type: void
Opcode _MAC_NET_MSG_who_response:
 Name: playerSerialNumber
  Type: DWORD
 Name: beginTextToken
  Type: unsigned short
 Name: separator
  Type: char
 Name: endTextToken
  Type: unsigned short
 Name: filteredCount
  Type: int
 Name: noActiveCharCount
  Type: int
 Name: count
  Type: int
 Name: totalPlayers
  Type: int
 Name: totalLines
  Type: short
  Type: void
Opcode _MAC_NET_MSG_wherePlayer:
 Name: target
  Type: char
 Name: source
  Type: char
 Name: found
  Type: unsigned char
 Name: zoneid
  Type: int
  Type: long
  Type: long
  Type: long
 Name: data
  Type: long
  Type: void
Opcode _MAC_NET_MSG_weatherMsg:
 Name: type
  Type: int
 Name: severity
  Type: int
  Type: void
Opcode _MAC_NET_MSG_weatherChgMsg:
 Name: rain
  Type: int
 Name: snow
  Type: int
 Name: severity
  Type: int
 Name: duration
  Type: int
  Type: void
Opcode _MAC_NET_MSG_zserver_statmsg:
 Name: playername
  Type: char
 Name: zoneid
  Type: int
 Name: reason
  Type: ZONE_REQ_REASON
 Name: status
  Type: ZONE_REQ_STATUS
  Type: void
Opcode _MAC_NET_MSG_zoneSky:
 Name: skyType
  Type: int
  Type: void
Opcode _MAC_NET_MSG_zoneHeader:
 Name: charname
  Type: char
 Name: zone
  Type: char
 Name: name
  Type: char
 Name: desc
  Type: char
 Name: fogOn
  Type: unsigned char
 Name: fogBaseRed
  Type: unsigned char
 Name: fogBaseGreen
  Type: unsigned char
 Name: fogBaseBlue
  Type: unsigned char
 Name: fogBaseStart
  Type: float
 Name: fogBaseEnd
  Type: float
 Name: gravity
  Type: float
 Name: outdoor
  Type: unsigned char
 Name: rainchance
  Type: unsigned char
 Name: rainduration
  Type: unsigned char
 Name: snowchance
  Type: unsigned char
 Name: snowduration
  Type: unsigned char
 Name: specialdates
  Type: unsigned char
 Name: specialcodes
  Type: unsigned char
 Name: timezone
  Type: char
 Name: sky
  Type: unsigned char
 Name: water_music
  Type: short
 Name: normal_music_day
  Type: short
 Name: normal_music_night
  Type: short
 Name: exp_modifier
  Type: float
 Name: safe_x
  Type: float
 Name: safe_y
  Type: float
 Name: safe_z
  Type: float
 Name: max_z
  Type: float
 Name: min_z
  Type: float
 Name: min_clip
  Type: float
 Name: max_clip
  Type: float
 Name: forage_novice
  Type: int
 Name: forage_medium
  Type: int
 Name: forage_advanced
  Type: int
 Name: fishing_novice
  Type: int
 Name: fishing_medium
  Type: int
 Name: fishing_advanced
  Type: int
 Name: sky_lock
  Type: int
 Name: graveyard_tme
  Type: unsigned short
 Name: scriptPeriodicHour
  Type: int
 Name: scriptPeriodicMinute
  Type: int
 Name: scriptPeriodicFast
  Type: int
 Name: scriptPlayerDead
  Type: int
 Name: scriptNpcDead
  Type: int
 Name: scriptPlayerEntering
  Type: int
  Type: void
Opcode _MAC_NET_MSG_zonecmdx:
 Name: fname
  Type: char
 Name: routenum
  Type: int
  Type: void
Opcode _MAC_NET_MSG_zone_address_t:
 Name: hostname
  Type: char
 Name: port
  Type: short
  Type: void